'use strict';
(() => {
 const button=document.createElement('button');button.textContent='備份／還原';document.querySelector('.research-controls').append(button);
 const dialog=document.createElement('dialog');dialog.className='library-dialog';dialog.setAttribute('aria-label','備份還原');const heading=document.createElement('h2');heading.textContent='文件資料備份';const message=document.createElement('p');message.textContent='備份包含文件、縮圖、分類、專案、書目、筆記、分析紀錄、研究 Skills、共同規則、AI 目錄與專案副本記錄；不含 API 金鑰、Codex 登入或外掛程式。還原會取代目前藏經資料，自動分析會停用；副本目錄需重新選擇並確認，還原不會直接寫入外部目錄。';const backup=document.createElement('button');backup.textContent='建立備份';const restore=document.createElement('button');restore.textContent='還原備份';const close=document.createElement('button');close.textContent='關閉';const output=document.createElement('p');output.setAttribute('role','status');dialog.append(heading,message,backup,restore,close,output);document.body.append(dialog);button.onclick=()=>dialog.showModal();close.onclick=()=>dialog.close();const bridge=window.desktopReader;restore.disabled=!bridge;
 async function digest(bytes){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');}
 async function encode(){const zip=new JSZip(),metadata=[];for(const record of await store.all()){const {data,cover,...rest}=record;metadata.push({...rest,hasCover:!!cover});zip.file('documents/'+record.id+'.bin',data);if(cover)zip.file('covers/'+record.id+'.png',cover instanceof Blob?await cover.arrayBuffer():cover);}const snapshot={format:'cangjing-backup',version:4,created:new Date().toISOString(),books:metadata,positions:await ReaderData.all('positions'),annotations:await ReaderData.all('annotations'),organization:await ReaderData.all('organization'),research:bridge?await bridge.backupResearch():null};zip.file('manifest.json',JSON.stringify(snapshot));return zip.generateAsync({type:'uint8array',compression:'DEFLATE'});}
 async function decode(bytes){const zip=await JSZip.loadAsync(bytes);const file=zip.file('manifest.json');if(!file)throw Error('缺少備份清單');const text=await file.async('string');if(text.length>100000000)throw Error('備份清單過大');const m=JSON.parse(text);if(m.format!=='cangjing-backup'||![1,2,3,4].includes(m.version)||!Array.isArray(m.books)||m.books.length>10000)throw Error('備份版本不相容');const books=[],seen=new Set();for(const row of m.books){if(!row||!/^[a-f0-9]{64}$/.test(row.id)||seen.has(row.id)||typeof row.title!=='string')throw Error('文件清單不正確');seen.add(row.id);const binary=zip.file('documents/'+row.id+'.bin');if(!binary)throw Error('備份缺少文件');const data=await binary.async('arraybuffer');if(await digest(data)!==row.id)throw Error('文件雜湊不符，未還原');let cover=null;if(row.hasCover){const image=zip.file('covers/'+row.id+'.png');if(!image)throw Error('備份缺少縮圖');cover=new Blob([await image.async('uint8array')],{type:'image/png'});}const {hasCover,...record}=row;books.push({...record,data,cover});}for(const key of ['positions','annotations','organization'])if(!Array.isArray(m[key])||m[key].some(row=>!row||typeof row.id!=='string'))throw Error('研究資料格式不正確');return {books,positions:m.positions,annotations:m.annotations,organization:m.organization,research:m.research||{jobs:[]}};}
 backup.onclick=async()=>{backup.disabled=true;restore.disabled=true;try{output.textContent='正在建立備份…';const bytes=await encode();if(bridge){const saved=await bridge.backupSave(bytes);output.textContent=saved?'備份已儲存':'已取消';}else{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes]));a.download='Cangjing-backup.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);output.textContent='備份已下載';}}catch(e){output.textContent='備份失敗：'+e.message;}finally{backup.disabled=false;restore.disabled=!bridge;}};
 restore.onclick=async()=>{if(!confirm('還原會取代目前藏經資料。請先建立備份；確定繼續？'))return;backup.disabled=true;restore.disabled=true;try{const bytes=await bridge.backupOpen();if(!bytes){output.textContent='已取消';return;}output.textContent='正在驗證備份…';const snapshot=await decode(bytes);const previousResearch=await bridge.backupResearch();await bridge.backupRestoreResearch(snapshot.research);try{await LibraryStore.restore(snapshot);}catch(e){await bridge.backupRestoreResearch(previousResearch);throw e;}output.textContent='還原完成，正在重新載入。';location.reload();}catch(e){output.textContent='還原失敗：'+e.message;}finally{backup.disabled=false;restore.disabled=!bridge;}};
 window.CangjingBackup={encode,decode};
})();
