'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EvidenceModel=api;})(typeof window==='object'?window:globalThis,()=>{
 const VERDICTS={supported:'支持',partial:'部分支持',unsupported:'不支持',unclear:'無法判斷'};
 const COLUMNS={rq:'研究問題',theory:'理論',constructs:'構念',operationalization:'操作化',method:'方法',results:'結果',discussion:'作者解釋',contribution:'貢獻',boundary:'限制'};
 function matrix(jobs){return jobs.map(j=>({documentId:j.id,title:j.title,versionId:j.versionId,created:j.created,cells:Object.fromEntries(Object.keys(COLUMNS).map(k=>{const g=['results','discussion'].includes(k)?j.result?.imrad?.sections?.[k]:j.result?.imrad?.logic?.[k];return [k,g||{status:'notReported',reason:'選定版本沒有此欄位',rows:[]}];}))}));}
 function tokens(text){return (text.toLowerCase().match(/[a-z0-9]{2,}|[\u3400-\u9fff]/gu)||[]);}
 function rank(pages,claim){const terms=new Set(tokens(claim));return pages.map((p,index)=>({p,index,score:tokens(p.text).reduce((n,t)=>n+(terms.has(t)?1:0),0)})).sort((a,b)=>b.score-a.score||a.index-b.index).map(x=>x.p);}
 function parse(text){const value=JSON.parse(text.replace(/^\s*```(?:json)?\s*/i,'').replace(/\s*```\s*$/,''));if(!value||typeof value!=='object'||Array.isArray(value))throw Error('回覆必須是 JSON 物件');return value;}
 function judgment(raw,sources){if(!Object.hasOwn(VERDICTS,raw.verdict)||typeof raw.reason!=='string'||!raw.reason.trim()||raw.reason.length>3000)throw Error('查核格式不正確');const valid=(Array.isArray(raw.evidence)?raw.evidence:[]).slice(0,12).filter(e=>e&&typeof e.quote==='string'&&e.quote.trim()&&e.quote.length<=1200&&sources.some(s=>s.documentId===e.documentId&&s.page===e.page&&s.text.includes(e.quote))).map(e=>({documentId:e.documentId,page:e.page,quote:e.quote}));const invalid=valid.length!==(raw.evidence||[]).length;return {verdict:invalid||!valid.length?'unclear':raw.verdict,reason:invalid?'來源引文或頁碼無效；不能確認支持關係。':raw.reason,evidence:valid,invalid};}
 function aggregate(parts){const grounded=parts.filter(p=>p.evidence.length),v=new Set(grounded.map(p=>p.verdict));const verdict=v.has('partial')||v.has('supported')&&v.has('unsupported')?'partial':v.has('supported')?'supported':v.has('unsupported')?'unsupported':'unclear';return {verdict,reason:parts.map(p=>p.reason).join('\n').slice(0,12000),evidence:[...new Map(parts.flatMap(p=>p.evidence).map(e=>[JSON.stringify(e),e])).values()]};}
 function claimsFromDraft(text){if(typeof text!=='string'||!text.trim()||text.length>20000)throw Error('草稿須為 1–20,000 字');let offset=0;return text.split('\n').flatMap(line=>{const start=offset;offset+=line.length+1;if(!line.trim())return [];if(line.length>1600)throw Error('每行主張最多 1,600 字，請拆分');return [{text:line,start,end:start+line.length,role:'user'}];});}
 function applyRevisions(original,claims,proposals,selected){const ids=new Set(selected);let result=original;const chosen=proposals.filter(p=>ids.has(p.id)).map(p=>{const c=claims.find(c=>c.id===p.claimId);if(!c||original.slice(c.start,c.end)!==p.before||p.before!==c.text||typeof p.after!=='string'||!p.after.trim())throw Error('修訂與原稿版本不符');return {...p,start:c.start,end:c.end};}).sort((a,b)=>b.start-a.start);let last=Infinity;for(const p of chosen){if(p.end>last)throw Error('修訂範圍重疊');result=result.slice(0,p.start)+p.after+result.slice(p.end);last=p.start;}return result;}
 function coverage(job){const complete=job.state==='completed';return {total:job.claims?.length||0,judged:complete?(job.results||[]).filter(r=>r.verdict!=='unclear').length:0,unclear:complete?(job.results||[]).filter(r=>r.verdict==='unclear').length:0,unjudged:complete?Math.max(0,job.claims.length-(job.results||[]).length):job.claims?.length||0};}
 return {VERDICTS,COLUMNS,matrix,rank,parse,judgment,aggregate,claimsFromDraft,applyRevisions,coverage};
});
