'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ImradReading=api;})(typeof window==='object'?window:globalThis,()=>{
 const SECTIONS={introduction:'Introduction · 建立問題',methods:'Methods · 取得與分析證據',results:'Results · 呈現結果',discussion:'Discussion · 解釋與貢獻'};
 const STAGES={known:'Known',gap:'Gap',rq:'RQ',theory:'Theory/Hypothesis',constructs:'Constructs',operationalization:'Operationalization',method:'Method',evidence:'Evidence',claim:'Claim',contribution:'Contribution',boundary:'Boundary/Limitations'};
 const STATUS={reported:'有來源內容',notReported:'未報告／未取得',notApplicable:'不適用'};
 function background(value){if(value==null)return null;if(!value||value.confirmed!==true||typeof value.id!=='string'||! /^[a-zA-Z0-9-]{1,80}$/.test(value.id)||typeof value.name!=='string'||!value.name.trim()||value.name.length>120||typeof value.text!=='string'||!value.text.trim()||value.text.length>3000||JSON.stringify(value.text).length>3500||!Number.isSafeInteger(value.confirmedAt)||value.confirmedAt<=0)throw Error('研究背景必須明確選擇並確認，且有名稱與內容');return {id:value.id,name:value.name,text:value.text,confirmed:true,confirmedAt:value.confirmedAt};}
 function parse(raw,pages,study=null){if(!raw||raw.schemaVersion!==1)throw Error('IMRaD 格式不正確');study=background(study);let rejected=0;const rows=values=>(Array.isArray(values)?values:[]).slice(0,20).flatMap(v=>{if(!v||typeof v.value!=='string'||!v.value.trim()||v.value.length>1600||!Number.isInteger(v.page)||typeof v.quote!=='string'||!v.quote.length||v.quote.length>600||!pages.some(p=>p.page===v.page&&p.text.includes(v.quote))){rejected++;return [];}return [{value:v.value,page:v.page,quote:v.quote,certainty:v.certainty==='extracted'?'extracted':'inferred'}];});
 const groups=(input,keys)=>Object.fromEntries(Object.keys(keys).map(key=>{const g=input?.[key]||{},items=rows(g.rows);return [key,{status:items.length?'reported':['notReported','notApplicable'].includes(g.status)?g.status:'notReported',reason:typeof g.reason==='string'?g.reason.slice(0,800):'',rows:items}];}));
 const sections=groups(raw.sections,SECTIONS),logic=groups(raw.logic,STAGES);
 const assessments=key=>(Array.isArray(raw[key])?raw[key]:[]).slice(0,3).flatMap(v=>{if(!Object.hasOwn(STAGES,v?.stage)){rejected++;return [];}return rows([v]).map(row=>({...row,stage:v.stage,certainty:'inferred'}));});
 const links=(Array.isArray(raw.links)?raw.links:[]).slice(0,20).flatMap(v=>{if(!Object.hasOwn(STAGES,v?.from)||!Object.hasOwn(STAGES,v?.to)||Object.keys(STAGES).indexOf(v.to)!==Object.keys(STAGES).indexOf(v.from)+1){rejected++;return [];}return rows([v]).map(row=>({...row,from:v.from,to:v.to,relation:'argument-support',certainty:'inferred'}));});
 const mapping=study?(Array.isArray(raw.mapping)?raw.mapping:[]).slice(0,20).flatMap(v=>{if(typeof v?.studyQuote!=='string'||!v.studyQuote.trim()||v.studyQuote.length>600||!study.text.includes(v.studyQuote)){rejected++;return [];}return rows([v]).map(row=>({...row,studyQuote:v.studyQuote,certainty:'inferred'}));}):[];
 if(!study&&raw.mapping?.length)rejected+=raw.mapping.length;
 return {schemaVersion:1,sections,logic,links,strongest:assessments('strongest'),weakest:assessments('weakest'),mapping,mappingStatus:study?'confirmed':'missing',rejected};
 }
 function merge(values){const list=values.filter(Boolean);if(!list.length)return null;const unique=rows=>[...new Map(rows.map(r=>[JSON.stringify(r),r])).values()];const groups=keys=>Object.fromEntries(Object.keys(keys).map(key=>{const gs=list.map(v=>(keys===SECTIONS?v.sections:v.logic)[key]),rows=unique(gs.flatMap(g=>g.rows));return [key,{status:rows.length?'reported':gs.every(g=>g.status==='notApplicable')?'notApplicable':'notReported',reason:[...new Set(gs.map(g=>g.reason).filter(Boolean))].join('；'),rows}];}));return {schemaVersion:1,sections:groups(SECTIONS),logic:groups(STAGES),links:unique(list.flatMap(v=>v.links)),strongest:unique(list.flatMap(v=>v.strongest)),weakest:unique(list.flatMap(v=>v.weakest)),mapping:unique(list.flatMap(v=>v.mapping)),mappingStatus:list.some(v=>v.mappingStatus==='confirmed')?'confirmed':'missing',rejected:list.reduce((n,v)=>n+(v.rejected||0),0)};}
 function presentation(data,id,study){const sources=r=>[{documentId:id,page:r.page,quote:r.quote,certainty:r.certainty}],section=(key,name,rows,note)=>({key,name,note,rows:rows.map(r=>({value:r.value+(r.studyQuote?'\n我的研究依據：'+r.studyQuote:''),sources:sources(r)}))});const all=[];
 for(const [key,name]of Object.entries(SECTIONS)){const g=data.sections[key];all.push(section(key,'1 · '+name,g.rows,STATUS[g.status]+(g.reason?' · '+g.reason:'')));}
 all.push(section('logic-note','2 · 研究邏輯',[],'Known → Gap → RQ → Theory/Hypothesis → Constructs → Operationalization → Method → Evidence → Claim → Contribution → Boundary/Limitations。箭頭為論證順序，不表示因果。'));
 for(const [key,name]of Object.entries(STAGES)){const g=data.logic[key];all.push(section(key,name,g.rows,STATUS[g.status]+(g.reason?' · '+g.reason:'')));}
 for(const key of ['links','strongest','weakest'])all.push(section(key,({links:'相鄰論證支承 · AI 判讀',strongest:'最強環節 · AI 判讀',weakest:'最弱環節 · AI 判讀'})[key],data[key].map(r=>({...r,value:(r.stage?STAGES[r.stage]+'：':r.from?STAGES[r.from]+' → '+STAGES[r.to]+'：':'')+r.value})),data[key].length?'':'尚無可核對的整篇判斷'));
 all.push(section('mapping','3 · Paper ↔ My Study',data.mapping,study?'已確認背景：'+study.name+' · '+new Date(study.confirmedAt).toLocaleString()+'。以下為候選建議；來源與研究背景分開核對。':'缺少已選擇並確認的研究背景，尚未映射。'));
 return all;
 }
 return {SECTIONS,STAGES,STATUS,background,parse,merge,presentation};
});
