'use strict';
(()=>{
 const bridge=window.desktopReader,el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;},types={concept:'概念',theory:'理論',method:'方法',finding:'發現'},certainty={extracted:'作者明載',inferred:'AI 推論',ambiguous:'待確認'},states={waiting:'等待 CLI',running:'萃取中',completed:'完成',partial:'部分完成／無文字層',failed:'失敗',cancelled:'已取消'};
 const dialog=el('dialog');dialog.className='knowledge-dialog';dialog.setAttribute('aria-label','研究知識圖');const heading=el('header'),close=el('button','關閉'),scope=el('select'),mode=el('select'),type=el('select'),source=el('select'),confidence=el('select'),search=el('input'),summary=el('p'),jobs=el('div'),canvas=el('div'),detail=el('aside'),list=el('div'),enable=el('button','啟用知識圖萃取'),extract=el('button','萃取範圍內 PDF'),next=el('button','下一組節點');let state={enabled:false,jobs:[]},map=null,offset=0,selected=null,lastStamp='',displayGraph=KnowledgeSchema.merge([]),scopeIds=[],graphStamp='',researchGraphs=[];let showGraph=false;try{showGraph=localStorage.getItem('cangjing-show-research-graph')==='true';}catch{}const graphBody=el('div');graphBody.className='knowledge-body';const graphToggle=el('button','顯示研究架構');graphToggle.setAttribute('aria-pressed',String(showGraph));graphToggle.onclick=()=>{showGraph=!showGraph;localStorage.setItem('cangjing-show-research-graph',String(showGraph));graphToggle.setAttribute('aria-pressed',String(showGraph));graphToggle.textContent=showGraph?'收起研究架構':'顯示研究架構';draw();};
 canvas.className='knowledge-canvas';canvas.setAttribute('aria-label','研究心智圖；亦可使用下方關係清單');summary.setAttribute('role','status');search.type='search';search.placeholder='搜尋概念或關係';search.setAttribute('aria-label','搜尋知識圖');scope.setAttribute('aria-label','知識圖範圍');type.setAttribute('aria-label','知識節點類型');source.setAttribute('aria-label','知識來源文件');confidence.setAttribute('aria-label','知識確定性');
 const certaintyOf=item=>item.sources.some(s=>s.certainty==='ambiguous')?'ambiguous':item.sources.some(s=>s.certainty==='inferred')?'inferred':'extracted';
 const option=(select,value,name)=>{const o=el('option',name);o.value=value;select.append(o);};mode.setAttribute('aria-label','理解架構來源');option(mode,'research','預讀理解（優先）');option(mode,'manual','手動知識圖譜');option(type,'','全部類型');for(const [key,name] of Object.entries(types))option(type,key,name);option(confidence,'','全部確定性');for(const [key,name] of Object.entries(certainty))option(confidence,key,name);
 const consent=el('dialog');consent.className='library-dialog';consent.setAttribute('aria-label','知識圖額外用量');const yes=el('button','啟用並記住知識圖萃取'),no=el('button','取消');consent.append(el('h2','另行啟用知識圖萃取'),el('p','知識圖萃取會另送 PDF 原頁文字至已登入 Codex CLI，可能增加帳戶用量。此選項獨立於背景研究摘要；啟用只允許手動萃取，匯入或預讀不會自動觸發；請再按「萃取範圍內 PDF」。已完成分段會快取，不重送；掃描頁不做 OCR。知識項目是 AI 候選，頁碼與原文引文仍需人工核對。'),yes,no);document.body.append(consent);no.onclick=()=>consent.close();
 yes.onclick=async()=>{try{state=await bridge.knowledgeConfigure(true);consent.close();await refresh();}catch(e){status(e.message);}};
 enable.onclick=async()=>{if(state.enabled){state=await bridge.knowledgeConfigure(false);await refresh();}else consent.showModal();};extract.onclick=async()=>{try{await enqueue(records.filter(r=>scopeIds.includes(r.id)&&r.type==='pdf'),true);await refresh();}catch(e){status(e.message);}};
 async function enqueue(rows,replaceWithCurrent=false){for(const r of rows){if(!replaceWithCurrent&&state.jobs.some(j=>j.id===r.id))continue;const pages=await ResearchUI.textPages(r.id);state=await bridge.knowledgeEnqueue({id:r.id,title:r.title,pages,replaceWithCurrent});}}
 function scopes(){const old=scope.value;scope.replaceChildren();option(scope,'all','全部文件');for(const p of LibraryExtras.projects())option(scope,'project:'+p.id,'專案 · '+p.name);for(const r of records.filter(r=>r.type==='pdf'))option(scope,'doc:'+r.id,'文件 · '+r.title);if([...scope.options].some(o=>o.value===old))scope.value=old;}
 function selectedIds(){if(scope.value.startsWith('doc:'))return records.filter(r=>r.id===scope.value.slice(4)).map(r=>r.id);if(scope.value.startsWith('project:')){const id=scope.value.slice(8),links=LibraryExtras.memberships();return records.filter(r=>(links[r.id]||[]).includes(id)).map(r=>r.id);}return records.filter(r=>r.type==='pdf').map(r=>r.id);}
 function sourceChoices(){const old=source.value;source.replaceChildren();option(source,'','全部來源');for(const r of records.filter(r=>r.type==='pdf'&&scopeIds.includes(r.id)))option(source,r.id,r.title);if([...source.options].some(o=>o.value===old))source.value=old;}
 function show(item){selected=item?.id||null;detail.replaceChildren();if(!item){detail.append(el('h3','選擇一個節點或關係'),el('p','查看直接相鄰節點與原文證據。每個項目皆為待核對候選。'));return;}detail.append(el('h3',item.name||[displayGraph.nodes.find(n=>n.id===item.source)?.name,item.relation,displayGraph.nodes.find(n=>n.id===item.target)?.name].join(' → ')));const neighbors=displayGraph.edges.filter(e=>(item.originalIds||[item.id]).includes(e.source)||(item.originalIds||[item.id]).includes(e.target));if(item.name)detail.append(el('p','原圖相鄰：'+(neighbors.map(e=>displayGraph.nodes.find(n=>n.id===((item.originalIds||[item.id]).includes(e.source)?e.target:e.source))?.name).filter(Boolean).join('、')||'無關係')));for(const relation of neighbors){const b=el('button','原關係：'+relation.relation);b.onclick=()=>show(relation);detail.append(b);}for(const evidence of item.sources){const r=records.find(r=>r.id===evidence.documentId);detail.append(el('p',(r?.title||'來源已移除')+' · 第 '+evidence.page+' 頁 · '+certainty[evidence.certainty]),el('blockquote',evidence.quote));const open=el('button','查看原文來源頁');open.disabled=!r;open.onclick=async()=>{dialog.close();await openBook(evidence.documentId);await webReader.show(evidence.page-1);};detail.append(open);}}
 function draw(){scopeIds=selectedIds();displayGraph=KnowledgeSchema.merge(state.jobs.filter(j=>scopeIds.includes(j.id)&&records.some(r=>r.id===j.id)&&(mode.value==='manual'||!researchGraphs.some(r=>r.id===j.id))).map(j=>j.graph).concat(researchGraphs.filter(j=>scopeIds.includes(j.id)&&mode.value!=='manual').map(j=>j.result.architecture)));const query=search.value.trim().toLocaleLowerCase(),valid=s=>(!source.value||s.documentId===source.value)&&(!confidence.value||s.certainty===confidence.value);const matched=displayGraph.nodes.filter(n=>(!type.value||type.value===n.type)&&n.sources.some(valid)&&(!query||n.name.toLocaleLowerCase().includes(query)||displayGraph.edges.some(e=>(e.source===n.id||e.target===n.id)&&e.relation.toLocaleLowerCase().includes(query))));if(offset>=matched.length)offset=0;const nodes=matched.slice(offset,offset+80),ids=new Set(nodes.map(n=>n.id)),edges=displayGraph.edges.filter(e=>ids.has(e.source)&&ids.has(e.target)&&e.sources.some(valid)).slice(0,200);const count=state.jobs.filter(j=>scopeIds.includes(j.id)&&j.state==='running').length;summary.textContent=count?'知識萃取中 · '+count+' 份文件；已完成部分可先查看':matched.length?`${matched.length} 個符合節點 · 本組 ${nodes.length} 節點／${edges.length} 關係（每組上限 80／200）`:'尚無可顯示知識；可啟用萃取、調整篩選，或檢查下方 CLI／文字層狀態。';next.disabled=matched.length<=80;next.onclick=()=>{offset=(offset+80)%matched.length;draw();};enable.textContent=state.enabled?'停用知識圖萃取':'啟用知識圖萃取';extract.disabled=!state.enabled;enable.disabled=!bridge;
 const relevant=[...state.jobs.filter(j=>scopeIds.includes(j.id)).map(j=>({...j,rowKey:j.id})),...(state.history||[]).filter(j=>scopeIds.includes(j.id)).map((j,i)=>({...j,title:j.title+' · 先前版本',archived:true,rowKey:'history-'+i+'-'+j.id}))];for(const old of [...jobs.children])if(!relevant.some(j=>j.rowKey===old.dataset.jobKey))old.remove();for(const j of relevant){const row=UsageUI.jobRow(jobs,j.rowKey,j),actions=row.querySelector('.job-actions');let button=actions.firstElementChild;if(!button){button=el('button');actions.append(button);}button.textContent=['running','waiting'].includes(j.state)?'取消萃取':'保留快取繼續';button.disabled=j.archived||['completed','partial'].includes(j.state);button.hidden=!!j.archived;button.onclick=async()=>{try{state=await (['running','waiting'].includes(j.state)?bridge.knowledgeCancel(j.id):bridge.knowledgeRetry(j.id));draw();}catch(e){status(e.message);}};}
 graphBody.hidden=!showGraph;list.hidden=!showGraph;graphToggle.setAttribute('aria-pressed',String(showGraph));graphToggle.textContent=showGraph?'收起研究架構':'顯示研究架構';if(!showGraph){map?.destroy();map=null;return;}
 const documentRows=records.filter(r=>scopeIds.includes(r.id)&&r.type==='pdf'&&(!source.value||r.id===source.value)),graphs=Object.fromEntries(documentRows.map(r=>[r.id,{nodes:nodes.filter(n=>n.sources.some(s=>s.documentId===r.id)).map(n=>({...n,sources:n.sources.filter(valid)})),edges:[]}])) ,results={};for(const j of researchGraphs.filter(j=>scopeIds.includes(j.id)&&mode.value!=='manual')){results[j.id]={};if(j.result.imrad){const filterRow=r=>(!query||r.value.toLocaleLowerCase().includes(query))&&(!source.value||source.value===j.id)&&(!confidence.value||confidence.value===(r.certainty||'inferred'));const data=structuredClone(j.result.imrad);for(const area of ['sections','logic'])for(const g of Object.values(data[area]))g.rows=g.rows.filter(filterRow);for(const k of ['strongest','weakest','links','mapping'])data[k]=data[k].filter(filterRow);if(!type.value)results[j.id].imrad=data;}for(const key of ['questions','methods','findings','limitations'])results[j.id][key]=(j.result[key]||[]).filter(v=>(!query||v.value.toLocaleLowerCase().includes(query))&&(!source.value||source.value===j.id)&&(!confidence.value||confidence.value==='ambiguous')&&(!type.value||({questions:'concept',methods:'method',findings:'finding',limitations:'finding'})[key]===type.value));}
 const root=MindMapModel.project(documentRows,graphs,results);let contentCount=0;const countItems=n=>{if(n.kind==='content')contentCount++;n.children.forEach(countItems);};countItems(root);summary.textContent=contentCount?matched.length+' 個符合節點 · '+contentCount+' 個內容節點 · '+edges.length+' 個原圖關係（於詳情查看）'+(matched.length>80?' · 圖譜節點分組顯示':''):'目前沒有符合的來源內容；可調整範圍與篩選。';const nextGraphStamp=JSON.stringify(root);if(nextGraphStamp===graphStamp&&map)return;graphStamp=nextGraphStamp;
 map?.destroy();map=new MindMapView(canvas,row=>{if(row.kind==='content'){show({id:row.id,name:row.label,sources:row.sources,originalIds:row.originalIds});return;}selected=row.id;detail.replaceChildren();detail.append(el('h3',row.label),el('p',row.kind==='group'?'此分支按原分析欄位或節點類型整理；連線表示閱讀分組。':'文件短題名為根；展開分支後選取內容查看證據。'));});map.set(root);
 list.replaceChildren();list.append(el('h3','節點與關係清單（鍵盤可操作）'));for(const n of nodes){const b=el('button',types[n.type]+' · '+n.name);b.onclick=()=>show(n);list.append(b);}for(const e of edges){const from=displayGraph.nodes.find(n=>n.id===e.source)?.name,to=displayGraph.nodes.find(n=>n.id===e.target)?.name;const b=el('button',from+' → '+e.relation+' → '+to);b.onclick=()=>show(e);list.append(b);}show([...displayGraph.nodes,...displayGraph.edges].find(n=>n.id===selected));}
 async function refresh(){if(bridge){state=await bridge.knowledgeStatus();researchGraphs=(await bridge.researchStatus()).jobs.filter(j=>j.result?.architecture||j.result?.imrad);}if(dialog.open){scopes();scopeIds=selectedIds();sourceChoices();draw();}}
 for(const field of [scope,mode,type,source,confidence])field.onchange=()=>{offset=0;if(field===scope){scopeIds=selectedIds();sourceChoices();}draw();};search.oninput=()=>{offset=0;draw();};close.onclick=()=>dialog.close();dialog.onclose=()=>{map?.destroy();map=null;};
 const toolbar=el('div');toolbar.className='knowledge-filters';toolbar.append(scope,mode);const advanced=el('details'),filters=el('div'),secondary=el('div');advanced.className='knowledge-advanced';advanced.append(el('summary','篩選與知識圖工具'));filters.className='knowledge-filters';filters.append(search,type,source,confidence);secondary.className='knowledge-actions';secondary.append(enable,extract,next);advanced.append(filters,secondary);const actions=el('div');actions.className='knowledge-actions';actions.append(graphToggle);for(const [label,fn] of [['放大',()=>map?.scale(1.2)],['縮小',()=>map?.scale(1/1.2)],['符合畫面',()=>map?.fit()],['重設',()=>map?.reset()],['展開全部',()=>map?.expandAll()],['收合分支',()=>map?.collapseAll()]]){const b=el('button',label);b.onclick=fn;actions.append(b);}for(const format of ['JSON','Markdown']){const b=el('button','匯出 '+format);b.onclick=()=>{const text=format==='JSON'?JSON.stringify({schemaVersion:1,scope:scope.value,documents:records.filter(r=>scopeIds.includes(r.id)).map(({id,title})=>({id,title})),analyzers:state.jobs.filter(j=>scopeIds.includes(j.id)).map(({id,adapter,schemaVersion})=>({documentId:id,adapter,schemaVersion})),graph:displayGraph},null,2):'# 藏經研究知識圖\n\n'+[...displayGraph.nodes,...displayGraph.edges].map(n=>'## '+(n.name||[displayGraph.nodes.find(x=>x.id===n.source)?.name,n.relation,displayGraph.nodes.find(x=>x.id===n.target)?.name].join(' → '))+'\n\n'+n.sources.map(s=>'> '+s.quote.replace(/\n/g,'\n> ')+'\n\n'+(records.find(r=>r.id===s.documentId)?.title||s.documentId)+' · PDF 第 '+s.page+' 頁 · '+certainty[s.certainty]).join('\n\n')).join('\n\n');const a=el('a');a.href=URL.createObjectURL(new Blob([text],{type:format==='JSON'?'application/json':'text/markdown;charset=utf-8'}));a.download='Cangjing-knowledge.'+(format==='JSON'?'json':'md');a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};secondary.append(b);}heading.append(el('h2','研究理解心智圖'),close);const main=graphBody;main.append(canvas,detail);dialog.append(heading,el('p','同次預讀的理解架構，顯示不另呼叫 AI。分組線表示閱讀層次；原關係與作者明載／AI 推論詳見來源。'),toolbar,actions,advanced,summary,main,list,jobs);document.body.append(dialog);
 async function open(){scopes();if(active?.type==='pdf')scope.value='doc:'+active.id;dialog.showModal();await refresh();dialog.scrollTop=0;}
 for(const target of ['.research-controls','.reader-tools']){const b=el('button','知識圖');b.onclick=open;document.querySelector(target).append(b);}
 let polling=false;setInterval(async()=>{if(!bridge||polling)return;polling=true;try{state=await bridge.knowledgeStatus();const stamp=JSON.stringify((await bridge.researchStatus()).jobs)+JSON.stringify(state)+JSON.stringify(LibraryExtras.memberships())+records.map(r=>r.id).join();if(dialog.open&&stamp!==lastStamp){lastStamp=stamp;await refresh();}}catch(e){if(dialog.open)status(e.message);}finally{polling=false;}},3000);window.KnowledgeUI={open,refresh,map:()=>map};
})();
