'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.KnowledgeSchema=api;})(typeof window==='object'?window:globalThis,()=>{
 const TYPES=['concept','theory','method','finding'],CERTAINTY=['extracted','inferred','ambiguous'];
 function parse(text,documentId,pages){let raw;try{raw=JSON.parse(text.replace(/^\s*```(?:json)?\s*/i,'').replace(/\s*```\s*$/,''));}catch{throw Error('知識萃取未回傳有效 JSON');}if(!raw||!Array.isArray(raw.nodes)||!Array.isArray(raw.edges)||raw.nodes.length>500||raw.edges.length>1000)throw Error('知識萃取格式或容量不正確');const nodes=[],edges=[],keys=new Map();let rejected=0;
 const evidence=r=>Number.isInteger(r.page)&&typeof r.quote==='string'&&r.quote.length>0&&r.quote.length<=600&&pages.some(p=>p.page===r.page&&p.text.includes(r.quote))&&CERTAINTY.includes(r.certainty);
 for(const r of raw.nodes){if(!r||typeof r.key!=='string'||keys.has(r.key)||typeof r.name!=='string'||!r.name.trim()||r.name.length>300||!TYPES.includes(r.type)||!evidence(r)){rejected++;continue;}const id=r.type+':'+r.name.trim();keys.set(r.key,id);nodes.push({id,name:r.name.trim(),type:r.type,sources:[{documentId,page:r.page,quote:r.quote,certainty:r.certainty}]});}
 for(const r of raw.edges){if(!r||!keys.has(r.source)||!keys.has(r.target)||r.source===r.target||typeof r.relation!=='string'||!r.relation.trim()||r.relation.length>300||!evidence(r)){rejected++;continue;}edges.push({id:JSON.stringify([keys.get(r.source),keys.get(r.target),r.relation.trim()]),source:keys.get(r.source),target:keys.get(r.target),relation:r.relation.trim(),sources:[{documentId,page:r.page,quote:r.quote,certainty:r.certainty}]});}
 return merge([{schemaVersion:1,nodes,edges,rejected}]);
 }
 function merge(graphs){const nodes=new Map(),edges=new Map();let rejected=0;for(const graph of graphs){rejected+=graph?.rejected||0;for(const [items,target] of [[graph?.nodes||[],nodes],[graph?.edges||[],edges]])for(const item of items){let row=target.get(item.id);if(!row){row={...item,sources:[]};target.set(item.id,row);}for(const source of item.sources){if(!row.sources.some(s=>JSON.stringify(s)===JSON.stringify(source)))row.sources.push({...source});}}}return {schemaVersion:1,nodes:[...nodes.values()],edges:[...edges.values()].filter(e=>nodes.has(e.source)&&nodes.has(e.target)),rejected};}
 function validateStored(graph,documentId,pages){if(!graph||graph.schemaVersion!==1||!Array.isArray(graph.nodes)||!Array.isArray(graph.edges)||graph.nodes.length>100000||graph.edges.length>200000)throw Error('知識圖備份版本或容量不正確');const keys=new Set();const sources=item=>Array.isArray(item.sources)&&item.sources.length>0&&item.sources.every(s=>s.documentId===documentId&&CERTAINTY.includes(s.certainty)&&Number.isInteger(s.page)&&typeof s.quote==='string'&&s.quote.length>0&&s.quote.length<=600&&pages.some(p=>p.page===s.page&&p.text.includes(s.quote)));for(const n of graph.nodes){if(!n||typeof n.name!=='string'||n.name.length>300||!TYPES.includes(n.type)||n.id!==n.type+':'+n.name||keys.has(n.id)||!sources(n))throw Error('知識節點來源不正確');keys.add(n.id);}for(const e of graph.edges)if(!e||!keys.has(e.source)||!keys.has(e.target)||typeof e.relation!=='string'||e.relation.length>300||e.id!==JSON.stringify([e.source,e.target,e.relation])||!sources(e))throw Error('知識關係來源不正確');return merge([graph]);}
 return {TYPES,CERTAINTY,parse,merge,validateStored};
});
