'use strict';
(()=>{
 class MindMapView{
  constructor(host,onSelect){this.host=host;this.onSelect=onSelect;this.collapsed=new Set();this.zoom=1;this.pan={x:0,y:0};this.host.tabIndex=0;this.host.setAttribute('role','region');this.host.setAttribute('aria-label','研究心智圖，可拖曳平移；加減鍵縮放，Home 符合畫面');this.world=document.createElement('div');this.world.className='mindmap-world';this.world.setAttribute('role','tree');this.world.setAttribute('aria-label','文件研究分支');this.host.replaceChildren(this.world);this.onWheel=e=>{e.preventDefault();const r=this.host.getBoundingClientRect();this.scale(e.deltaY<0?1.12:1/1.12,{x:e.clientX-r.left,y:e.clientY-r.top});};this.host.addEventListener('wheel',this.onWheel,{passive:false});this.host.onpointerdown=e=>{if(e.target.closest('button')||e.button!==0)return;this.drag={id:e.pointerId,x:e.clientX,y:e.clientY,pan:{...this.pan}};this.host.setPointerCapture(e.pointerId);this.host.classList.add('panning');};this.host.onpointermove=e=>{if(this.drag?.id!==e.pointerId)return;this.pan={x:this.drag.pan.x+e.clientX-this.drag.x,y:this.drag.pan.y+e.clientY-this.drag.y};this.transform();};this.host.onpointerup=this.host.onpointercancel=e=>{this.drag=null;this.host.classList.remove('panning');};this.host.onkeydown=e=>{if(e.target!==this.host)return;if(['+','=','-','Home','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))e.preventDefault();if(['+','='].includes(e.key))this.scale(1.2);else if(e.key==='-')this.scale(1/1.2);else if(e.key==='Home')this.fit();else if(e.key.startsWith('Arrow')){this.pan.x+=({ArrowLeft:48,ArrowRight:-48})[e.key]||0;this.pan.y+=({ArrowUp:48,ArrowDown:-48})[e.key]||0;this.transform();}};this.observer=new ResizeObserver(()=>{if(this.autoFit&&this.data)this.fit();});this.observer.observe(host);}
  set(root){this.root=root;this.collapsed.clear();const contents=[];const walk=n=>{if(n.kind==='content')contents.push(n);n.children.forEach(walk);};walk(root);if(contents.length>8){const collapse=n=>{if(n.kind==='group')this.collapsed.add(n.id);n.children.forEach(collapse);};collapse(root);}this.render();this.autoFit=false;this.fit();if(this.zoom<.8){this.zoom=.8;const root=this.data.nodes[0];this.pan={x:16-root.x*this.zoom,y:this.host.clientHeight/2-(root.y+root.height/2)*this.zoom};this.autoFit=false;this.transform();}}
  render(){const ctx=document.createElement('canvas').getContext('2d');ctx.font='14px "Noto Sans TC", "Microsoft JhengHei", sans-serif';this.data=MindMapModel.layout(this.root,{collapsed:this.collapsed,measure:s=>ctx.measureText(s).width});this.world.replaceChildren();this.world.style.width=this.data.width+'px';this.world.style.height=this.data.height+'px';const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('width',this.data.width);svg.setAttribute('height',this.data.height);svg.setAttribute('aria-hidden','true');svg.classList.add('mindmap-lines');for(const e of this.data.edges){const p=document.createElementNS(ns,'path'),mid=(e.x1+e.x2)/2;p.setAttribute('d',`M ${e.x1} ${e.y1} H ${mid-8} Q ${mid} ${e.y1} ${mid} ${e.y1+(e.y2>=e.y1?8:-8)} V ${e.y2+(e.y2>=e.y1?-8:8)} Q ${mid} ${e.y2} ${mid+8} ${e.y2} H ${e.x2}`);if(Math.abs(e.y1-e.y2)<16)p.setAttribute('d',`M ${e.x1} ${e.y1} H ${e.x2}`);svg.append(p);}this.world.append(svg);
   for(const row of this.data.nodes){const box=document.createElement('div');box.className='mindmap-node '+row.kind;box.dataset.nodeId=row.id;box.style.cssText=`left:${row.x}px;top:${row.y}px;width:${row.width}px;height:${row.height}px`;box.setAttribute('role','treeitem');box.setAttribute('aria-level',row.depth+1);box.setAttribute('aria-selected',String(this.selected===row.id));if(row.children.length)box.setAttribute('aria-expanded',String(!this.collapsed.has(row.id)));const label=document.createElement('button');label.className='mindmap-label';label.title=row.label;label.setAttribute('aria-label',row.label+(row.kind==='content'?' · '+row.badge:''));for(const text of row.lines){const line=document.createElement('span');line.textContent=text||' ';label.append(line);}if(row.kind==='content'){const badge=document.createElement('small');badge.textContent=row.badge;label.append(badge);}label.onclick=()=>{this.selected=row.id;for(const n of this.world.querySelectorAll('[role=treeitem]'))n.setAttribute('aria-selected',String(n.dataset.nodeId===row.id));this.onSelect(row);};label.onfocus=()=>{if(label.matches(':focus-visible'))this.reveal(row);};box.append(label);if(row.children.length){const toggle=document.createElement('button');toggle.className='mindmap-toggle';toggle.textContent=(this.collapsed.has(row.id)?'+':'−')+' '+row.children.length;toggle.setAttribute('aria-label',(this.collapsed.has(row.id)?'展開':'收合')+' '+row.label);toggle.setAttribute('aria-expanded',String(!this.collapsed.has(row.id)));toggle.onclick=()=>{const screen={x:row.x*this.zoom+this.pan.x,y:(row.y+row.height/2)*this.zoom+this.pan.y};this.collapsed.has(row.id)?this.collapsed.delete(row.id):this.collapsed.add(row.id);this.autoFit=false;this.render();const next=this.data.nodes.find(n=>n.id===row.id);this.pan={x:screen.x-next.x*this.zoom,y:screen.y-(next.y+next.height/2)*this.zoom};this.transform();const target=[...this.world.querySelectorAll('.mindmap-node')].find(n=>n.dataset.nodeId===row.id)?.querySelector('.mindmap-toggle');target?.focus({preventScroll:true});};box.append(toggle);}this.world.append(box);}this.transform();}
  reveal(row){const left=this.pan.x+row.x*this.zoom,top=this.pan.y+row.y*this.zoom,right=left+row.width*this.zoom,bottom=top+row.height*this.zoom;if(left<0||right>this.host.clientWidth||top<0||bottom>this.host.clientHeight){this.autoFit=false;this.pan={x:this.host.clientWidth/2-(row.x+row.width/2)*this.zoom,y:this.host.clientHeight/2-(row.y+row.height/2)*this.zoom};this.transform();}}
  transform(){this.world.style.transform=`translate(${this.pan.x}px,${this.pan.y}px) scale(${this.zoom})`;this.host.dataset.zoom=this.zoom.toFixed(3);}
  scale(factor,point={x:this.host.clientWidth/2,y:this.host.clientHeight/2}){const next=Math.max(.08,Math.min(2.5,this.zoom*factor)),ratio=next/this.zoom;this.pan={x:point.x-(point.x-this.pan.x)*ratio,y:point.y-(point.y-this.pan.y)*ratio};this.zoom=next;this.autoFit=false;this.transform();}
  fit(){if(!this.data)return;this.zoom=Math.max(.0001,Math.min(1.15,(this.host.clientWidth-32)/this.data.width,(this.host.clientHeight-32)/this.data.height));this.pan={x:(this.host.clientWidth-this.data.width*this.zoom)/2,y:(this.host.clientHeight-this.data.height*this.zoom)/2};this.autoFit=true;this.transform();}
  reset(){this.set(this.root);}
  expandAll(){this.collapsed.clear();this.render();this.fit();}
  collapseAll(){const visit=n=>{if(n.kind==='group')this.collapsed.add(n.id);n.children.forEach(visit);};visit(this.root);this.render();this.fit();}
  destroy(){this.observer.disconnect();this.host.removeEventListener('wheel',this.onWheel);this.host.onpointerdown=this.host.onpointermove=this.host.onpointerup=this.host.onpointercancel=this.host.onkeydown=null;this.host.replaceChildren();}
 }
 window.MindMapView=MindMapView;
})();
