'use strict';
(()=>{
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;},cache=new Map(),pending=new Set();
 const dialog=el('dialog');dialog.className='library-dialog cover-dialog';dialog.setAttribute('aria-label','PDF 文件封面');const heading=el('div'),close=el('button','關閉'),input=el('input'),image=el('img'),message=el('p'),preview=el('button','預覽頁面'),save=el('button','設為文件封面'),reset=el('button','恢復第一頁'),actions=el('div'),label=el('label','封面頁碼');heading.className='dialog-heading';heading.append(el('h2','PDF 文件封面'),close);input.type='number';input.min=1;input.setAttribute('aria-label','封面頁碼');label.append(input);image.alt='指定頁面完整比例預覽';image.className='cover-preview';actions.className='cover-actions';actions.append(preview,save,reset);message.setAttribute('role','status');dialog.append(heading,el('p','選擇 PDF 的任一頁作為文獻庫縮圖。不修改 PDF，也不改變閱讀位置。'),label,actions,message,image);document.body.append(dialog);let id=null,serial=0,url=null,draft=null,rendering=false,menu=null;
 function page(record,value){const n=Number(value);if(!Number.isInteger(n)||n<1||n>record.sections)throw Error('封面頁碼須為 1 至 '+record.sections+' 的整數');return n;}
 async function render(record,number){const key=record.id+':'+number;if(cache.has(key))return cache.get(key);const blob=(record.coverPage||1)===number&&record.cover instanceof Blob?record.cover:await PdfReader.preview(record.data,number);if(!(blob instanceof Blob)||!blob.size)throw Error('頁面預覽失敗，原封面保留');cache.set(key,blob);if(cache.size>8)cache.delete(cache.keys().next().value);return blob;}
 function show(blob){if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);image.src=url;image.hidden=false;}
 async function set(documentId,value,blob){if(pending.has(documentId))throw Error('此文獻封面正在更新');pending.add(documentId);try{const record=await store.get(documentId);if(!record||record.type!=='pdf')throw Error('PDF 文獻不存在');const number=page(record,value),cover=blob||await render(record,number);if(!(cover instanceof Blob)||!cover.size)throw Error('封面產生失敗，原封面保留');await store.update(documentId,current=>({...current,cover,coverPage:number,coverRevision:Date.now(),previewError:null}));const latest=await store.get(documentId);records=records.map(r=>r.id===documentId?latest:r);if(active?.id===documentId){active.cover=cover;active.coverPage=number;}drawShelf();status('文件封面已更新為第 '+number+' 頁');return latest;}finally{pending.delete(documentId);}}
 async function previewPage(){const token=++serial;rendering=true;save.disabled=true;preview.disabled=true;message.textContent='正在預覽…';try{const record=await store.get(id);if(!record)throw Error('PDF 文獻不存在');const number=page(record,input.value),blob=await render(record,number);if(token!==serial)return;draft={number,blob};show(blob);message.textContent='第 '+number+' / '+record.sections+' 頁 · 尚未套用';save.disabled=false;}catch(e){if(token===serial){draft=null;message.textContent=e.message;}}finally{if(token===serial){rendering=false;preview.disabled=false;}}}
 preview.onclick=previewPage;input.oninput=()=>{draft=null;save.disabled=true;message.textContent='請先預覽頁面';};save.onclick=async()=>{if(!draft||rendering)return;save.disabled=true;try{await set(id,draft.number,draft.blob);dialog.close();}catch(e){message.textContent='更新失敗，原封面保留：'+e.message;save.disabled=false;}};reset.onclick=async()=>{input.value=1;await previewPage();if(draft){try{await set(id,1,draft.blob);dialog.close();}catch(e){message.textContent='恢復失敗，原封面保留：'+e.message;}}};close.onclick=()=>dialog.close();dialog.onclose=()=>{serial++;draft=null;rendering=false;preview.disabled=false;if(url)URL.revokeObjectURL(url);url=null;image.removeAttribute('src');};
 async function open(documentId){const record=await store.get(documentId);if(!record||record.type!=='pdf'){status('請選擇 PDF 文獻');return;}id=documentId;input.max=record.sections;input.value=record.coverPage||1;dialog.showModal();await previewPage();}
 function context(event,documentId,number){event.preventDefault();menu?.remove();menu=el('div');menu.className='cover-context';menu.setAttribute('role','menu');menu.setAttribute('aria-label','PDF 頁面縮圖');const button=el('button','設為文件封面');button.setAttribute('role','menuitem');button.onclick=async()=>{menu?.remove();menu=null;try{await set(documentId,number);}catch(e){status('更新失敗，原封面保留：'+e.message);}};menu.append(button);document.body.append(menu);const rect=event.currentTarget.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(event.clientX||rect.left,innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(8,Math.min(event.clientY||rect.bottom,innerHeight-menu.offsetHeight-8))+'px';button.focus();}
 document.addEventListener('pointerdown',e=>{if(menu&&!menu.contains(e.target)){menu.remove();menu=null;}},true);document.addEventListener('keydown',e=>{if(menu&&e.key==='Escape'){e.preventDefault();menu.remove();menu=null;}},true);
 window.PdfCover={open,set,context};
})();
