'use strict';
(() => {
 const bridge=window.desktopReader;if(!bridge)return;
 const hosts=new Map(),errors=new Map();let plugins=[],serial=0;
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const dialog=el('dialog');dialog.className='library-dialog';dialog.setAttribute('aria-label','外掛管理');const title=el('h2','本機外掛'),close=el('button','關閉'),install=el('button','從資料夾安裝'),list=el('div'),output=el('pre');output.className='plugin-output';const download=el('button','儲存外掛結果');download.onclick=()=>{const a=el('a');a.href=URL.createObjectURL(new Blob([output.textContent],{type:'text/markdown;charset=utf-8'}));a.download='Cangjing-plugin-output.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};dialog.append(download);dialog.append(title,el('p','外掛在隔離頁面執行。啟用即授予下列權限；停用會移除執行頁面。第一版不提供網路、全文、AI 或原生程式碼權限。'),close,install,list,output);document.body.append(dialog);close.onclick=()=>dialog.close();
 const button=el('button','外掛');document.querySelector('.research-controls').append(button);button.onclick=()=>{render();dialog.showModal();};install.onclick=async()=>{try{plugins=await bridge.pluginsInstall();render();}catch(e){output.textContent=e.message;}};
 function teardown(id){const host=hosts.get(id);if(host){for(const p of host.pending.values()){clearTimeout(p.timer);p.reject(Error('外掛已停用'));}host.frame.remove();hosts.delete(id);}}
 function mount(plugin){if(hosts.has(plugin.id))return;const frame=el('iframe');frame.hidden=true;frame.setAttribute('sandbox','allow-scripts');frame.title=plugin.name;frame.src='cangjing-plugin://'+plugin.id+'/index.html';const host={frame,token:crypto.randomUUID(),pending:new Map(),ready:false};hosts.set(plugin.id,host);frame.onload=()=>frame.contentWindow.postMessage({type:'plugin:init',token:host.token},'*');document.body.append(frame);setTimeout(()=>{if(!host.ready&&hosts.has(plugin.id)){errors.set(plugin.id,'外掛載入逾時');teardown(plugin.id);render();}},5000);}
 function command(plugin,id,context=null){const host=hosts.get(plugin.id);if(!host?.ready)return Promise.reject(Error('外掛尚未就緒'));const requestId=++serial;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{host.pending.delete(requestId);reject(Error('外掛命令逾時'));},10000);host.pending.set(requestId,{resolve,reject,timer});host.frame.contentWindow.postMessage({type:'plugin:command',token:host.token,id:requestId,command:id,context},'*');});}
 addEventListener('message',async event=>{
  const entry=[...hosts.entries()].find(([,h])=>h.frame.contentWindow===event.source);if(!entry||event.origin!=='null')return;const [id,host]=entry,m=event.data;if(!m||typeof m!=='object'||m.token!==host.token||typeof m.type!=='string')return;
  if(m.type==='plugin:ready'){host.ready=true;errors.delete(id);render();return;}
  if(m.type==='plugin:result'&&Number.isSafeInteger(m.id)){const p=host.pending.get(m.id);if(p){clearTimeout(p.timer);host.pending.delete(m.id);m.error?p.reject(Error(String(m.error).slice(0,1000))):p.resolve(String(m.result).slice(0,20000));}return;}
  if(m.type!=='plugin:rpc'||!Number.isSafeInteger(m.id)||typeof m.method!=='string'||m.method.length>100)return;
  try{const authorization=await bridge.pluginsRpc({id,method:m.method,args:m.args});let result=authorization;if(m.method==='documents.metadata.read')result=ResearchUI.snapshot().documents;if(m.method==='projects.read')result=ResearchUI.snapshot().projects;if(m.method==='notes.export')result=await ProjectNotes.markdown();if(!hosts.has(id))return;host.frame.contentWindow.postMessage({type:'plugin:reply',token:host.token,id:m.id,result},'*');}catch(e){host.frame.contentWindow.postMessage({type:'plugin:reply',token:host.token,id:m.id,error:e.message},'*');}
 });
 function render(){list.replaceChildren();for(const plugin of plugins){const row=el('article');row.className='plugin-row';row.append(el('h3',plugin.name+' '+plugin.version),el('p','API '+plugin.apiVersion+' · 權限：'+(plugin.permissions.join('、')||'無')),el('p',errors.get(plugin.id)||plugin.error||(plugin.enabled?(hosts.get(plugin.id)?.ready?'已啟用':'載入中'):'已停用')));const toggle=el('button',plugin.enabled?'停用':'啟用');toggle.onclick=async()=>{try{plugins=await bridge.pluginsEnable(plugin.id,!plugin.enabled);teardown(plugin.id);const next=plugins.find(p=>p.id===plugin.id);if(next.enabled)mount(next);render();}catch(e){errors.set(plugin.id,e.message);render();}};row.append(toggle);for(const c of plugin.contributions.commands){const b=el('button',c.title);b.disabled=!hosts.get(plugin.id)?.ready;b.onclick=async()=>{try{output.textContent=await command(plugin,c.id);}catch(e){errors.set(plugin.id,e.message);output.textContent=e.message;render();}};row.append(b);}list.append(row);}}
 window.CangjingPlugins={renderPanels:async(container,documentId)=>{for(const p of plugins.filter(p=>p.enabled))for(const panel of p.contributions.panels||[]){const row=el('section');row.className='plugin-detail-panel';row.append(el('h3',p.name+'／'+panel.title));const text=el('pre','載入外掛面板…');text.className='plugin-output';row.append(text);container.append(row);try{text.textContent=await command(p,'panel:'+panel.id,{documentId});}catch(e){text.textContent=e.message;}}}};bridge.pluginsList().then(result=>{plugins=result;for(const p of plugins)if(p.enabled)mount(p);render();}).catch(e=>status(e.message));
 addEventListener('pagehide',()=>{for(const id of hosts.keys())teardown(id);});
})();
