'use strict';
(() => {
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const dialog=el('dialog');dialog.className='library-dialog research-details';dialog.setAttribute('aria-label','專案筆記');const close=el('button','關閉');close.onclick=()=>dialog.close();const projects=el('select');projects.setAttribute('aria-label','筆記研究專案');const form=el('form'),body=el('textarea'),evidenceList=el('div'),saved=el('div'),source=el('select'),page=el('input'),quote=el('textarea');let evidence=[],editing=null;
 body.rows=5;body.maxLength=20000;body.setAttribute('aria-label','專案筆記內容');source.setAttribute('aria-label','來源文件');page.type='number';page.min='1';page.value='1';page.setAttribute('aria-label','來源頁碼或章節序號');quote.maxLength=10000;quote.setAttribute('aria-label','原文引文');const add=el('button','加入文件證據');add.type='button';add.onclick=()=>{const record=records.find(r=>r.id===source.value);if(!record)return;const p=Number(page.value);if(!Number.isInteger(p)||p<1||p>record.sections)return status('請填入有效頁碼或章節序號');evidence.push({documentId:record.id,title:record.title,mode:record.type==='pdf'?'pdf':'web',page:p,quote:quote.value.trim()});quote.value='';renderEvidence();};
 function renderEvidence(){evidenceList.replaceChildren();evidence.forEach((e,i)=>{const row=el('article');row.append(el('p',e.title+' · '+(e.mode==='pdf'?'第 '+e.page+' 頁':'第 '+e.page+' 章')),el('blockquote',e.quote));const remove=el('button','移除證據');remove.type='button';remove.onclick=()=>{evidence.splice(i,1);renderEvidence();};row.append(remove);evidenceList.append(row);});}
 const save=el('button','儲存專案筆記');save.type='submit';form.append(el('label','筆記內容'),body,el('label','證據來源文件'),source,el('label','PDF 頁碼／EPUB 章節序號'),page,el('label','原文引文（請核對文件）'),quote,add,evidenceList,save);form.onsubmit=async e=>{e.preventDefault();if(!projects.value)return status('請先建立研究專案');if(!body.value.trim()&&!evidence.length)return;await ReaderData.put('annotations',{id:editing||crypto.randomUUID(),kind:'project-note',projectId:projects.value,text:body.value.trim(),evidence:structuredClone(evidence),updated:Date.now()});editing=null;body.value='';evidence=[];renderEvidence();await renderSaved();status('專案筆記已儲存');};
 async function renderSaved(){saved.replaceChildren();for(const note of (await ReaderData.all('annotations')).filter(n=>n.kind==='project-note'&&n.projectId===projects.value)){const row=el('article');row.className='saved-note';row.append(el('p',note.text));for(const evidence of note.evidence||[]){row.append(el('blockquote',evidence.title+' · '+evidence.page+'：'+evidence.quote));const open=el('button',records.some(r=>r.id===evidence.documentId)?'回到來源':'來源已移除');open.disabled=!records.some(r=>r.id===evidence.documentId);open.onclick=async()=>{dialog.close();await openBook(evidence.documentId,evidence.mode);await webReader.show(evidence.page-1);};row.append(open);}const edit=el('button','編輯');edit.onclick=()=>{editing=note.id;body.value=note.text;evidence=structuredClone(note.evidence||[]);renderEvidence();};const remove=el('button','刪除專案筆記');remove.onclick=async()=>{if(confirm('刪除此專案筆記？')){await ReaderData.remove('annotations',note.id);await renderSaved();}};row.append(edit,remove);saved.append(row);}}
 projects.onchange=()=>{editing=null;body.value='';evidence=[];renderEvidence();renderSaved();};
 const exportButton=el('button','匯出 Markdown');exportButton.onclick=async()=>{const text=await markdown(projects.value);const a=el('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));a.download='Cangjing-notes.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};dialog.append(el('h2','研究專案筆記'),close,projects,exportButton,form,saved);document.body.append(dialog);
 const button=el('button','專案筆記');button.onclick=async()=>{projects.replaceChildren();for(const p of LibraryExtras.projects()){const option=el('option',p.name);option.value=p.id;projects.append(option);}source.replaceChildren();for(const r of records){const option=el('option',r.title);option.value=r.id;source.append(option);}await renderSaved();dialog.showModal();};document.querySelector('.research-controls').append(button);
 async function markdown(projectId){const all=await ReaderData.all('annotations');const selected=projectId?all.filter(n=>n.kind==='project-note'&&n.projectId===projectId):all.filter(n=>n.kind!=='highlight');return '# 藏經研究筆記\n\n'+selected.map(n=>{const project=LibraryExtras.projects().find(p=>p.id===n.projectId);const source=records.find(r=>r.id===n.bookId);return '## '+(project?.name||source?.title||'來源已移除')+'\n\n'+(n.text||'')+'\n\n'+(n.evidence||[{title:source?.title||n.bookId,page:n.chapter,quote:n.quote}]).filter(e=>e.quote).map(e=>'> '+e.quote.replace(/\n/g,'\n> ')+'\n\n來源：'+e.title+' · '+e.page).join('\n\n');}).join('\n\n---\n\n');}
 window.ProjectNotes={markdown};
})();
