'use strict';
(() => {
 const bridge=window.desktopReader,labels={title:'標題',authors:'作者',year:'年份',journal:'期刊',doi:'DOI',summary:'摘要',questions:'研究問題',theory:'理論與概念',conclusions:'結論',methods:'方法',findings:'主要發現',limitations:'限制',tags:'建議標籤'};
 let queue={enabled:false,jobs:[]},extracting=false,pending=[],detailsId=null;
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const background=el('button','未分析');background.id='reader-analysis-status';background.className='reader-analysis-status';background.title='查看目前文件的背景研究分析';background.onclick=()=>{if(active?.type==='pdf')showDetails(active.id,{analysis:true});};document.querySelector('#reader footer').insertBefore(background,document.querySelector('#position'));function updateBackground(){const record=active?.type==='pdf'?records.find(r=>r.id===active.id)||active:null;const job=record&&queue.jobs.find(j=>j.id===record.id);background.hidden=!record;background.textContent=UsageUI.backgroundStatus(job,record?.analysisPreparation);background.setAttribute('aria-label',(record?.title||'目前文件')+' · '+background.textContent+'；查看分析詳情');}document.addEventListener('reader-document-changed',updateBackground);updateBackground();
 const controls=el('div');controls.className='research-controls';const view=el('button','清單檢視');view.setAttribute('aria-pressed','false');let listMode=localStorage.getItem('cangjing-library-view')==='list';
 function applyView(){document.body.classList.toggle('document-list',listMode);view.textContent=listMode?'縮圖檢視':'清單檢視';view.setAttribute('aria-pressed',String(listMode));}view.onclick=()=>{listMode=!listMode;localStorage.setItem('cangjing-library-view',listMode?'list':'grid');applyView();};controls.append(view);applyView();document.querySelector('.library-head').after(controls);
 const automation=el('button','自動分析：未啟用');automation.disabled=!bridge;controls.append(automation);
 const stateFilter=el('select');stateFilter.setAttribute('aria-label','篩選閱讀狀態');for(const [value,name] of [['','全部閱讀狀態'],['待讀','待讀'],['閱讀中','閱讀中'],['已讀','已讀'],['暫停','暫停']]){const o=el('option',name);o.value=value;stateFilter.append(o);}stateFilter.onchange=drawShelf;const tagFilter=el('input');tagFilter.type='search';tagFilter.placeholder='篩選標籤';tagFilter.setAttribute('aria-label','篩選標籤');tagFilter.oninput=drawShelf;controls.append(stateFilter,tagFilter);
 const consent=el('dialog');consent.className='library-dialog';consent.setAttribute('aria-label','自動研究分析設定');consent.append(el('h2','啟用 Codex 全文分析'),el('p','PDF 的全部可抽取文字會依頁碼分段送至您已登入的 Codex 服務，可能計入帳戶用量。同次分析整理研究內容與可溯源理解架構，顯示架構不另呼叫 AI；知識圖預設收起。程式會記住選擇，之後匯入的 PDF 將在背景分析。掃描頁不做 OCR；沒有已登入 CLI 時只使用 PDF metadata，不改用 OpenAI API。'));
 const enable=el('button','啟用並記住'),disable=el('button','停用自動分析'),close=el('button','關閉');consent.append(enable,disable,close);document.body.append(consent);close.onclick=()=>consent.close();automation.onclick=()=>consent.showModal();
 enable.onclick=async()=>{try{queue=await bridge.researchConfigure(true);consent.close();for(const r of records.filter(r=>r.type==='pdf'))schedule(r);refresh();}catch(e){status(e.message);}};disable.onclick=async()=>{queue=await bridge.researchConfigure(false);consent.close();refresh();};
 const dialog=el('dialog');dialog.className='library-dialog research-details';dialog.setAttribute('aria-label','文件研究資訊');document.body.append(dialog);
 function coverage(job){return job.textPages?Math.round(job.processedPages.length/job.textPages*100):0;}
 const states={waiting:'等待',running:'分析中',completed:'完成',partial:'部分完成／無文字層',failed:'失敗',cancelled:'已取消'};
 function decorate(entry,record){
  const info=LibraryExtras.summary(record.id),summary=el('p','分類：'+info.category+' · 專案：'+(info.projects.join('、')||'未加入'));summary.className='document-associations';entry.append(summary);
  const job=queue.jobs.find(j=>j.id===record.id);const state=el('p',record.type==='pdf'?(job?`${UsageUI.status(job)} · ${job.processedPages.length}/${job.textPages} 文字頁 (${coverage(job)}%)`:(record.analysisPreparation?.message||'PDF metadata · 尚未分析')):'EPUB');state.className='analysis-status';entry.append(state);
  const actions=entry.querySelector('.entry-actions');const details=el('button','文件資訊');details.onclick=()=>showDetails(record.id);actions.append(details,LibraryExtras.projectAssignment(record.id));
  if(record.tags?.length)entry.append(el('p','標籤：'+record.tags.join('、')));if(record.readingState)entry.append(el('p','閱讀狀態：'+record.readingState));
  if(record.type==='pdf')entry.classList.add('pdf-document');
 }
 function schedule(record){if(!queue.enabled||record.type!=='pdf'||queue.jobs.some(j=>j.id===record.id)||pending.some(r=>r.id===record.id))return;pending.push(record);setTimeout(drain,0);}
 async function drain(){if(extracting||!pending.length||!queue.enabled)return;extracting=true;const record=pending.shift();try{const cli=await bridge.researchCheck();if(!cli.ok){record.analysisPreparation={state:'waiting',message:'等待 CLI；僅使用 PDF metadata'};await store.put(record);refresh();status('Codex CLI 未安裝或未登入；僅使用 PDF metadata。可於文件資訊重試。');return;}const pages=await textPages(record.id);queue=await bridge.researchEnqueue({id:record.id,title:record.title,pages});refresh();}catch(e){record.analysisPreparation={state:'failed',message:'文字擷取失敗：'+e.message};await store.put(record);refresh();status('背景分析準備失敗：'+e.message);}finally{extracting=false;if(pending.length)setTimeout(drain,0);}}
 async function showDetails(id,{analysis=false}={}){const record=await store.get(id);if(!record)return;detailsId=id;dialog.replaceChildren();const heading=el('div');heading.className='dialog-heading';heading.append(el('h2',record.title));const x=el('button','關閉');x.onclick=()=>dialog.close();heading.append(x);dialog.append(heading,el('p','原始書目：'+Object.entries(record.metadata||{title:record.title,authors:record.author}).filter(([,v])=>v).map(([k,v])=>(labels[k]||k)+'：'+v).join(' · ')),el('p','人工書目與 AI 候選分開保存；空欄位保持空白。'));dialog.append(LibraryExtras.projectAssignment(id),LibraryExtras.assignment(id));
  const form=el('form');form.className='bibliography-form';const fields={};for(const key of ['title','authors','year','journal','doi']){const label=el('label',labels[key]);const input=el('input');input.value=record.bibliography?.[key]||'';input.maxLength=2000;input.setAttribute('aria-label','人工'+labels[key]);label.append(input);form.append(label);fields[key]=input;}const tags=el('input');tags.value=(record.tags||[]).join('、');tags.maxLength=1000;tags.setAttribute('aria-label','文件標籤');const tagLabel=el('label','標籤（以逗號或頓號分隔）');tagLabel.append(tags);form.append(tagLabel);const reading=el('select');reading.setAttribute('aria-label','閱讀狀態');for(const state of ['待讀','閱讀中','已讀','暫停']){const option=el('option',state);reading.append(option);}reading.value=record.readingState||'待讀';const stateLabel=el('label','閱讀狀態');stateLabel.append(reading);form.append(stateLabel);const save=el('button','儲存人工書目與狀態');save.type='submit';form.append(save);form.onsubmit=async e=>{e.preventDefault();record.bibliography=Object.fromEntries(Object.entries(fields).map(([k,n])=>[k,n.value.trim()]));record.tags=[...new Set(tags.value.split(/[,，、]/).map(t=>t.trim()).filter(Boolean))].slice(0,100);record.readingState=reading.value;record.bibliographyConfirmedAt=Date.now();await store.put(record);records=records.map(r=>r.id===id?record:r);drawShelf();status('人工書目與狀態已儲存');};dialog.append(form);
  const job=queue.jobs.find(j=>j.id===id);if(record.type==='pdf'){
   const analysisHeading=el('h3','文件背景分析'),analysisState=el('p',analysisDescription(job));analysisHeading.className='research-analysis-heading';analysisState.className='research-current-status';dialog.append(analysisHeading,analysisState);
   if(!queue.enabled){const start=el('button','啟用背景分析');start.onclick=()=>{dialog.close();consent.showModal();};dialog.append(start);}const retry=el('button',job?'重試／繼續分析':'分析全文');retry.className='research-retry';retry.disabled=!queue.enabled||job?.state==='running';retry.onclick=async()=>{try{if(job)queue=await bridge.researchRetry(id);else schedule(record);refresh();dialog.close();}catch(e){status(e.message);}};dialog.append(retry);if(job){const current=el('button','以目前研究規則重新分析');current.disabled=!queue.enabled||['waiting','running'].includes(job.state);current.onclick=async()=>{try{queue=await bridge.researchEnqueue({id:record.id,title:record.title,pages:await textPages(record.id),replaceWithCurrent:true,forceReanalysis:true});refresh();dialog.close();}catch(e){status(e.message);}};dialog.append(current);}if(job){const cancel=el('button','取消分析');cancel.className='research-cancel';cancel.hidden=!['waiting','running'].includes(job.state);cancel.onclick=async()=>{queue=await bridge.researchCancel(id);refresh();dialog.close();};dialog.append(cancel);}
   if(job?.result?.architecture){const graph=job.result.architecture;dialog.append(el('h3','研究理解架構'),el('p',graph.nodes.length+' 個來源節點／'+graph.edges.length+' 個關係 · 來自同次預讀分析'));const show=el('button','查看研究架構');show.onclick=()=>{dialog.close();KnowledgeUI.open();};dialog.append(show);}if(job){const host=el('div');host.className='research-job';UsageUI.jobRow(host,job.id,job);dialog.append(host);for(const key of Object.keys(labels)){dialog.append(el('h3','AI 候選／'+labels[key]));const values=job.result?.[key]||[];if(!values.length)dialog.append(el('p','缺值／未取得可核對來源'));for(const item of values){const block=el('article');block.className='analysis-evidence';block.append(el('p',item.value),el('blockquote','第 '+item.page+' 頁：'+item.quote));const go=el('button','查看來源頁');go.onclick=async()=>{dialog.close();await openBook(id);await webReader.show(item.page-1);};block.append(go);if(fields[key]){const confirm=el('button','採用後人工核對');confirm.onclick=()=>{fields[key].value=fields[key].value?fields[key].value+'；'+item.value:item.value;fields[key].focus();};block.append(confirm);}else{const edit=el('textarea');edit.value=record.researchNotes?.[key]?.find(x=>x.page===item.page&&x.quote===item.quote)?.value||item.value;edit.maxLength=10000;edit.setAttribute('aria-label','人工核對'+labels[key]);const confirm=el('button','儲存人工核對');confirm.onclick=async()=>{record.researchNotes||={};record.researchNotes[key]=[...(record.researchNotes[key]||[]).filter(x=>x.page!==item.page||x.quote!==item.quote),{...item,value:edit.value,confirmed:true,at:Date.now()}];await store.put(record);status('核對結果已儲存');};block.append(edit,confirm);}dialog.append(block);}}}
  }
  const history=(queue.history||[]).filter(j=>j.id===id);if(history.length){const section=el('details');section.append(el('summary','先前分析版本（'+history.length+'）'));history.forEach((old,i)=>{const host=el('div');UsageUI.jobRow(host,'research-history-'+i,old);section.append(host);});dialog.append(section);}
  window.CangjingPlugins?.renderPanels(dialog,id);if(!dialog.open)dialog.showModal();if(analysis)requestAnimationFrame(()=>dialog.querySelector('.research-analysis-heading')?.scrollIntoView({block:'start'}));
 }
 function analysisDescription(job){return job?UsageUI.backgroundStatus(job)+' · '+(job.done||0)+'/'+job.totalChunks+' 分段 · '+(job.processedPages?.length||0)+'/'+job.textPages+' 文字頁 · 全文件 '+job.totalPages+' 頁\n'+UsageUI.message(job.message):'尚未分析，只使用 PDF metadata';}
 function refresh(){document.dispatchEvent(new CustomEvent('research-status-changed'));updateBackground();if(dialog.open&&detailsId){const job=queue.jobs.find(j=>j.id===detailsId),host=dialog.querySelector('.research-job');if(job&&host)UsageUI.jobRow(host,job.id,job);const progress=dialog.querySelector('.research-current-status');if(progress)progress.textContent=analysisDescription(job);const retry=dialog.querySelector('.research-retry');if(retry)retry.disabled=!queue.enabled||job?.state==='running';const cancel=dialog.querySelector('.research-cancel');if(cancel)cancel.hidden=!job||!['waiting','running'].includes(job.state);}automation.textContent='自動分析：'+(queue.enabled?'已啟用':'未啟用');drawShelf();}
 const textInFlight=new Map();
 async function textPages(id){if(textInFlight.has(id))return textInFlight.get(id);const promise=readTextPages(id);textInFlight.set(id,promise);try{return await promise;}finally{textInFlight.delete(id);}}
 async function readTextPages(id){let record=await store.get(id);if(!record||record.type!=='pdf')throw Error('請選擇 PDF 文件');if(record.pdfTextPages)return record.pdfTextPages;const pages=await bridge?.researchPages(id)||await PdfReader.textPages(record.data);record=await store.get(id);if(!record)throw Error('來源文件已移除');record.pdfTextPages=pages;await store.put(record);records=records.map(r=>r.id===id?record:r);return pages;}
 window.ResearchUI={status:()=>queue,textPages,matches:r=>(!stateFilter.value||(r.readingState||'待讀')===stateFilter.value)&&(!tagFilter.value.trim()||(r.tags||[]).some(t=>t.includes(tagFilter.value.trim()))),clearFilters:()=>{stateFilter.value='';tagFilter.value='';},decorate,imported:schedule,details:showDetails,removed:async id=>{pending=pending.filter(r=>r.id!==id);await LibraryExtras.removeDocument(id);for(const n of await ReaderData.all('annotations'))if(n.bookId===id)await ReaderData.remove('annotations',n.id);if(bridge)queue=await bridge.researchForget(id);},snapshot:()=>({projects:LibraryExtras.projects(),documents:records.filter(r=>r.type==='pdf').map(({id,title,author,type,metadata,bibliography,tags,readingState})=>({id,title,author,type,metadata,bibliography,tags,readingState}))})};
 if(bridge){bridge.researchStatus().then(s=>{queue=s;if(s.error)status(s.error);refresh();for(const r of records)schedule(r);}).catch(e=>status(e.message));let stamp='';setInterval(async()=>{try{const next=await bridge.researchStatus();const updated=JSON.stringify(next);if(updated!==stamp){stamp=updated;queue=next;refresh();}}catch{}},2500);}
})();
