'use strict';
(()=>{
 const bridge=window.desktopReader,el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const dialog=el('dialog');dialog.className='library-dialog skills-dialog';dialog.setAttribute('aria-label','研究規則與 Skill');const heading=el('header'),close=el('button','關閉'),message=el('p'),list=el('div'),editor=el('textarea'),research=el('select'),knowledge=el('select');message.setAttribute('role','status');list.className='skills-list';editor.rows=9;editor.maxLength=65536;editor.setAttribute('aria-label','共同研究規則 AGENTS.md');research.setAttribute('aria-label','預讀分析預設 Skill');knowledge.setAttribute('aria-label','知識萃取預設 Skill');let state=null;
 close.onclick=()=>dialog.close();heading.append(el('h2','研究規則與 Skill'),close);
 const imports=el('div');imports.className='skill-actions';for(const [kind,label]of [['folder','匯入 Skill 資料夾'],['zip','匯入 Skill ZIP']]){const b=el('button',label);b.onclick=()=>act(()=>bridge.skillsImport(kind));imports.append(b);}
 const rulesLabel=el('label','共同研究規則 · AGENTS.md');rulesLabel.append(editor);const ruleActions=el('div');ruleActions.className='skill-actions';const importRules=el('button','匯入共同規則'),saveRules=el('button','儲存共同規則'),restore=el('button','恢復內建規則與 Skills');importRules.onclick=async()=>{try{const value=await bridge.skillsImportRules();if(value){editor.value=value.agents;message.textContent=value.normalized?'已載入草稿，儲存時統一使用 AGENTS.md。':'已載入 AGENTS.md 草稿，請檢查後儲存。';editor.focus();}}catch(e){message.textContent=e.message.replace(/^Error invoking remote method '[^']+': (?:Error: )?/,'');}};saveRules.onclick=()=>act(()=>bridge.skillsChange({agents:editor.value}));restore.onclick=()=>{if(confirm('恢復內建共同規則、Skills 與預設配置？使用者匯入的 Skill 會保留。'))act(()=>bridge.skillsChange({restoreDefaults:true}),true);};ruleActions.append(importRules,saveRules,restore);
 const presets=el('div');presets.className='skill-presets';for(const [select,label]of [[research,'預讀分析'],[knowledge,'知識萃取']]){const l=el('label',label+'預設 Skill');l.append(select);presets.append(l);}const saveDefault=el('button','儲存預設 Skill');saveDefault.onclick=()=>act(()=>bridge.skillsChange({defaults:{research:research.value,knowledge:knowledge.value}}));presets.append(saveDefault);
 dialog.append(heading,el('p','選擇研究流程，或匯入自己的 Skill。共同規則適用於新的研究工作；進行中的工作與保留進度重試會使用建立時的內容。'),el('p','匯入支援 UTF-8 的 SKILL.md 與 references 中的 Markdown／文字檔；不支援腳本型 Skill。匯入後先停用，可查看內容再啟用。'),message,imports,list,presets,rulesLabel,ruleActions);document.body.append(dialog);
 async function act(fn,reset=false){try{const draft=editor.value,dirty=state&&draft!==state.agents;state=await fn();draw();if(dirty&&!reset)editor.value=draft;message.textContent='已儲存；現有研究工作維持原快照。';}catch(e){message.textContent=e.message;}}
 function fill(select,selected=''){select.replaceChildren();const none=el('option','不套用 Skill');none.value='';select.append(none);for(const s of state?.skills||[]){if(!s.enabled)continue;const o=el('option',(s.body.match(/^#\s+(.+)/m)?.[1]||s.name)+' · '+s.name);o.value=s.name;select.append(o);}select.value=selected;}
 function draw(){list.replaceChildren();for(const s of state.skills){const row=el('article');row.className='skill-card';const title=el('h3',s.body.match(/^#\s+(.+)/m)?.[1]||s.name),name=el('p',s.name+' · '+s.source+' · '+s.version+' · '+(s.enabled?'已啟用':'已停用')),description=el('p',s.description),details=el('details');details.append(el('summary','查看 Skill 流程與參考'));for(const [file,content]of Object.entries(s.files)){details.append(el('h4',file),el('pre',content));}const actions=el('div');actions.className='skill-actions';const toggle=el('button',s.enabled?'停用':'啟用');toggle.setAttribute('aria-label',(s.enabled?'停用 ':'啟用 ')+s.name);toggle.onclick=()=>act(()=>bridge.skillsChange({id:s.name,enabled:!s.enabled}));actions.append(toggle);if(s.source!=='內建'){const remove=el('button','刪除');remove.setAttribute('aria-label','刪除 '+s.name);remove.onclick=()=>{if(confirm('刪除此使用者 Skill？既有研究快照會保留。'))act(()=>bridge.skillsChange({id:s.name,remove:true}));};actions.append(remove);}row.append(title,name,description,details,actions);list.append(row);}editor.value=state.agents;fill(research,state.defaults.research);fill(knowledge,state.defaults.knowledge);message.textContent=state.error||'';}
 async function open(){if(!bridge)return;state=await bridge.skillsStatus();draw();dialog.showModal();}
 async function populate(select,selected){state=await bridge.skillsStatus();fill(select,selected??state.defaults.research);}
 const button=el('button','研究規則／Skill');button.disabled=!bridge;button.onclick=()=>open().catch(e=>status(e.message));document.querySelector('.research-controls').append(button);window.ResearchSkills={open,populate};
})();
