'use strict';
(()=>{
 const bridge=window.desktopReader,el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};let current=null,state={jobs:[]},polling=false;
 function attach(reader,host){const heading=el('h3','AI 目錄'),note=el('p','手動辨識可讀文字的標題；AI 層級與分組是推論，不取代原始書籤。掃描頁不做 OCR。'),progress=el('p'),actions=el('div'),generate=el('button','生成 AI 目錄'),retry=el('button','保留進度重試'),cancel=el('button','取消生成'),headings=el('div'),usage=el('div');actions.className='toc-actions';actions.append(generate,retry,cancel);progress.setAttribute('role','status');host.replaceChildren(heading,note,actions,progress,headings,usage);current={reader,host,progress,generate,retry,cancel,headings,usage,stamp:''};
  generate.onclick=async()=>{if(!bridge)return;const old=state.jobs.find(j=>j.id===reader.record.id);if(!confirm('生成 AI 目錄會將全部可抽取頁面文字分段送至已登入 Codex CLI，可能增加帳戶用量。'+(old?'重新生成會保留舊目錄與用量。':'')+'確定送出？'))return;try{state=await bridge.tocEnqueue({id:reader.record.id,title:reader.record.title,pages:await ResearchUI.textPages(reader.record.id),replace:!!old});draw();}catch(e){progress.textContent=e.message;}};
  retry.onclick=async()=>{try{state=await bridge.tocRetry(reader.record.id);draw();}catch(e){progress.textContent=e.message;}};cancel.onclick=async()=>{try{state=await bridge.tocCancel(reader.record.id);draw();}catch(e){progress.textContent=e.message;}};refresh();
 }
 function draw(){const c=current;if(!c||c.reader.dead)return;const job=state.jobs.find(j=>j.id===c.reader.record.id);c.generate.disabled=!bridge||['waiting','running'].includes(job?.state);c.generate.textContent=job?'重新生成 AI 目錄':'生成 AI 目錄';c.retry.hidden=!job||['completed','partial'].includes(job.state);c.retry.disabled=['waiting','running'].includes(job?.state);c.cancel.hidden=!job||!['waiting','running'].includes(job.state);c.progress.textContent=job?(job.phase==='integrate'&&job.state==='running'?'正在整合目錄 · ':UsageUI.status(job)+' · ')+job.message+' · 已涵蓋 '+job.processedPages.length+'/'+(job.totalPages-job.missingTextPages.length)+' 文字頁'+(job.result?.rejected?' · 已排除 '+job.result.rejected+' 個無效來源':''):'尚未生成；切換或開啟此區不會呼叫 AI';if(job)UsageUI.jobRow(c.usage,job.id,job);const history=(state.history||[]).filter(j=>j.id===c.reader.record.id);const stamp=JSON.stringify([job?.result,history]);if(stamp===c.stamp)return;c.stamp=stamp;c.headings.replaceChildren();for(const h of job?.result?.headings||[]){const row=el('article');row.className='ai-toc-heading';row.style.marginLeft=((h.level-1)*10)+'px';const go=el('button',h.title+' · 第 '+h.page+' 頁');go.onclick=()=>{if(!c.reader.dead)c.reader.show(h.page-1).catch(e=>status(e.message));};const source=el('details');source.append(el('summary',(h.certainty==='extracted'?'原文標題':'推論標題')+' · AI 分組推論'),el('blockquote',h.quote));row.append(go,source);c.headings.append(row);}if(job&&!job.result?.headings.length)c.headings.append(el('p','尚無可核對的標題；原始目錄與頁面縮圖仍可使用。'));if(history.length){const details=el('details');details.append(el('summary','先前目錄版本（'+history.length+'）'));for(const [i,old]of history.entries()){const host=el('div');UsageUI.jobRow(host,'toc-history-'+i,old);details.append(host);for(const h of old.result?.headings||[]){const go=el('button',h.title+' · 第 '+h.page+' 頁');go.onclick=()=>{if(!c.reader.dead)c.reader.show(h.page-1).catch(e=>status(e.message));};details.append(go,el('blockquote',h.quote));}}c.headings.append(details);}}
 async function refresh(){if(!bridge)return;try{state=await bridge.tocStatus();draw();}catch(e){if(current&&!current.reader.dead)current.progress.textContent='目錄狀態讀取失敗：'+e.message;}}
 setInterval(async()=>{if(polling||!current||current.reader.dead)return;polling=true;try{await refresh();}finally{polling=false;}},2500);window.TocUI={attach,refresh};
})();
