'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.UsageUI=api;})(typeof window==='object'?window:globalThis,()=>{
 const number=v=>Number.isSafeInteger(v)&&v>=0?v:null,format=v=>v===null?'未回報':v.toLocaleString('zh-TW');
 function normalize(usage){const u=usage||{},input=number(u.input??u.inputTokens??u.input_tokens),output=number(u.output??u.outputTokens??u.output_tokens);return {input,output,total:number(u.total??u.totalTokens??u.total_tokens)??(input!==null&&output!==null?input+output:null),cached:number(u.cached??u.cachedInputTokens??u.cached_input_tokens??u.input_tokens_details?.cached_tokens),reasoning:number(u.reasoning??u.reasoningTokens??u.reasoningOutputTokens??u.reasoning_output_tokens??u.output_tokens_details?.reasoning_tokens)};}
 function aggregate(entries=[]){const rows=entries.map(e=>normalize(e.usage));return {total:rows.some(r=>r.total!==null)?rows.reduce((n,r)=>n+(r.total??0),0):null,partial:rows.some(r=>r.total===null||r.input===null||r.output===null),rows};}
 function summary(entries){const a=aggregate(entries);return a.total===null?'Token 用量：未回報':'已回報合計 '+format(a.total)+' Token'+(a.partial?'（部分未回報）':'');}
 function status(job,total=job.totalChunks??job.chunks?.length){const state=job.state==='running'?(job.execution==='processing'?'正在分析':'等待處理'):({waiting:'等待處理',completed:'完成',partial:'部分完成',failed:'失敗',cancelled:'已取消',interrupted:'上次中斷'})[job.state]||'準備中';return (Number.isInteger(total)?'已完成 '+(job.done||0)+'/'+total+' 段 · ':'')+state;}
 function message(text=''){return text.replaceAll('等待共用 CLI 排程','等待處理').replaceAll('共用 CLI 排程','處理佇列');}
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 function updateUsage(host,entries=[]){let component=host.querySelector(':scope > .usage-component');if(!component){component=el('div');component.className='usage-component';component.append(el('p'));const details=el('details'),label=el('summary','用量明細'),scroll=el('div');scroll.className='usage-scroll';details.append(label,scroll);component.append(details);host.append(component);}component.firstChild.textContent=summary(entries);const details=component.querySelector('details'),scroll=component.querySelector('.usage-scroll'),stamp=JSON.stringify(entries);if(component.dataset.stamp===stamp)return component;component.dataset.stamp=stamp;const position=scroll.scrollLeft;scroll.replaceChildren();const rows=aggregate(entries).rows,cached=rows.some(r=>r.cached!==null),reasoning=rows.some(r=>r.reasoning!==null),table=el('table'),head=el('tr');const columns=['工作','輸入','輸出','合計',...(cached?['輸入含快取']:[]),...(reasoning?['輸出含推理']:[])];for(const title of columns){const th=el('th',title);th.scope='col';head.append(th);}const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');entries.forEach((entry,i)=>{const u=rows[i],tr=el('tr'),label=Number.isInteger(entry.chunk)?'分段 '+(entry.chunk+1):entry.phase==='integrate'||entry.phase==='synthesize'?'整合 '+(entry.round===undefined?i+1:entry.round+1):entry.phase==='error'?'中斷回報':'請求 '+(i+1);for(const value of [label,format(u.input),format(u.output),format(u.total),...(cached?[format(u.cached)]:[]),...(reasoning?[format(u.reasoning)]:[])])tr.append(el('td',value));body.append(tr);const meta=el('tr'),cell=el('td');cell.colSpan=columns.length;cell.className='usage-meta';const date=entry.at?new Date(entry.at):null;cell.textContent=[date&&!Number.isNaN(date.getTime())?date.toLocaleString('zh-TW',{hour12:false}):null,entry.model?'模型：'+entry.model:null].filter(Boolean).join(' · ');if(cell.textContent){meta.append(cell);body.append(meta);}});table.append(body);if(entries.length)scroll.append(table);else scroll.append(el('p','服務尚未回報用量。'));if(cached||reasoning)scroll.append(el('small','快取為輸入子集，推理為輸出子集，不另加到合計。'));scroll.scrollLeft=position;return component;}
 function jobRow(host,key,job){let row=[...host.children].find(n=>n.dataset.jobKey===key);if(!row){row=el('article');row.dataset.jobKey=key;row.className='job-status';const title=el('h3'),state=el('p'),note=el('p'),usage=el('div'),actions=el('div');title.className='job-title';state.className='job-progress';note.className='job-message';usage.className='job-usage';actions.className='job-actions';row.append(title,state,note,usage,actions);host.append(row);}row.querySelector('.job-title').textContent=job.title||'';row.querySelector('.job-progress').textContent=status(job);const note=row.querySelector('.job-message');note.textContent=['failed','partial','cancelled','interrupted'].includes(job.state)?message(job.message):'';note.hidden=!note.textContent;updateUsage(row.querySelector('.job-usage'),job.usage);let provenance=row.querySelector('.skill-snapshot');if(job.instructionSnapshot){if(!provenance){provenance=el('details');provenance.className='skill-snapshot';provenance.append(el('summary','本次研究規則與 Skill'),el('p'),el('pre'));row.append(provenance);}const snap=job.instructionSnapshot;provenance.querySelector('p').textContent=(snap.skillId?snap.skillId+' · '+snap.version:'不套用 Skill')+' · 建立時的共同規則與流程';provenance.querySelector('pre').textContent=snap.instructions;}return row;}
 return {normalize,aggregate,format,summary,status,message,updateUsage,jobRow};
});
