'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const M=require('../ebook-browser/evidence-model.js'),{EvidenceWorkbench,PROMPTS}=require('./evidence-workbench.cjs'),{ResearchQueue}=require('./research-queue.cjs'),{SkillManager}=require('./skill-manager.cjs'),{validate,instructionsFor}=require('./ai-service.cjs');
const id='a'.repeat(64),pages=[{page:1,text:'The study reports an association, not a causal effect.'},{page:2,text:'The sample is limited to adults in one city.'}],source={id,title:'Study',pages};
async function temporary(fn){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cangjing-evidence-'));try{await fn(dir);}finally{assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep));await fs.rm(dir,{recursive:true,force:true});}}
async function settle(q){for(let i=0;i<500;i++){await new Promise(r=>setTimeout(r,5));if(!q.active&&!q.jobs.some(j=>j.state==='waiting'))return;}throw Error('timeout');}
function service(fn){return {calls:[],settings:async()=>({model:'fixture'}),checkCli:async()=>({ok:true}),cancel(){},async run(input){validate(input);this.calls.push(input);return {text:JSON.stringify(await fn(JSON.parse(input.text),input)),model:'fixture',usage:{totalTokens:10}};}};}
async function bench(dir,fn){const skills=new SkillManager(dir,path.join(__dirname,'../research-skills'));await skills.init();const ai=service(fn),read=service(()=>({})),q=new EvidenceWorkbench(dir,{skills,service:ai,readingService:read});await q.load();return {q,ai,skills};}
test('wrong physical pages and invented quotes never yield support',()=>{for(const evidence of [[{documentId:id,page:3,quote:pages[0].text}],[{documentId:id,page:1,quote:'invented'}],[]]){const result=M.judgment({verdict:'supported',reason:'fixture',evidence},pages.map(p=>({...p,documentId:id})));assert.equal(result.verdict,'unclear');}assert.equal(M.judgment({verdict:'partial',reason:'qualified',evidence:[{documentId:id,page:1,quote:pages[0].text}]},pages.map(p=>({...p,documentId:id}))).verdict,'partial');});
test('support aggregation keeps contradictory evidence partial and incomplete work unjudged',()=>{const parts=['supported','unsupported'].map(verdict=>({verdict,reason:'fixture',evidence:[{documentId:id,page:1,quote:pages[0].text}]}));assert.equal(M.aggregate(parts).verdict,'partial');assert.equal(M.coverage({state:'failed',claims:[{}],results:[{verdict:'supported'}]}).judged,0);});
test('draft revisions preserve every unflagged character and reject mismatched versions',()=>{const original='第一句。\nSecond claim.\n\nLast unchanged.';const claims=M.claimsFromDraft(original).map((c,i)=>({...c,id:String(i)}));const p={id:'p',claimId:'1',before:'Second claim.',after:'Qualified claim.'};assert.equal(M.applyRevisions(original,claims,[p],['p']),'第一句。\nQualified claim.\n\nLast unchanged.');assert.throws(()=>M.applyRevisions(original,claims,[{...p,before:'wrong'}],['p']));});
test('manual new reading contract does not request architecture and archive load never calls AI',async()=>temporary(async dir=>{assert.ok(!instructionsFor({action:'reading'}).includes('include architecture:'));const ai=service(()=>({}));await fs.writeFile(path.join(dir,'research-queue.json'),JSON.stringify({enabled:true,jobs:[{id,state:'running'}]}));const q=new ResearchQueue(dir,{service:ai,archival:true});await q.load();assert.equal(q.enabled,false);assert.equal(q.jobs[0].state,'interrupted');assert.equal(ai.calls.length,0);}));
test('claim verification covers every selected readable passage with exact provenance and rules snapshot',async()=>temporary(async dir=>{const {q,ai}=await bench(dir,b=>({verdict:b.sources[0].page===1?'unsupported':'unclear',reason:'Association cannot establish causality',evidence:[{documentId:id,page:b.sources[0].page,quote:b.sources[0].text}]}));await q.create({type:'verify',claim:'The treatment causes improvement.',role:'user',sources:[source]});await settle(q);const j=q.jobs[0];assert.equal(j.state,'completed');assert.equal(j.done,2);assert.equal(j.results[0].verdict,'unsupported');assert.ok(j.instructionSnapshot.agentsContentHash);assert.equal(ai.calls.length,2);assert.ok(j.results[0].evidence.every(e=>pages[e.page-1].text.includes(e.quote)));const restored=q.prepare(q.export());assert.equal(restored.jobs[0].state,'completed');}));
test('failed second passage never passes; manual retry keeps completed passages',async()=>temporary(async dir=>{let fail=true;const {q,ai}=await bench(dir,b=>{if(b.sources[0].page===2&&fail)throw Error('network fixture');return {verdict:'supported',reason:'fixture',evidence:[{documentId:id,page:b.sources[0].page,quote:b.sources[0].text}]};});await q.create({type:'verify',claim:'The study reports an association.',role:'author',sources:[source]});await settle(q);assert.equal(q.jobs[0].state,'failed');assert.equal(M.coverage(q.jobs[0]).unjudged,1);assert.equal(q.jobs[0].results.length,0);fail=false;await q.retry(q.jobs[0].jobId);await settle(q);assert.equal(ai.calls.length,3);assert.equal(q.jobs[0].state,'completed');}));
test('restored interrupted work is not auto resumed and source tampering is rejected',async()=>temporary(async dir=>{const {q}=await bench(dir,()=>({}));q.stopping=true;await q.create({type:'verify',claim:'Fixture claim',role:'user',sources:[source]});const raw=q.export();assert.equal(q.prepare(raw).jobs[0].state,'interrupted');const tampered=structuredClone(raw);tampered.jobs[0].sources[0].pages[0].text='tampered';assert.throws(()=>q.prepare(tampered),/雜湊/);await q.restore(raw);assert.equal(q.jobs[0].state,'interrupted');}));
test('revision requires completed flagged draft check and acceptance creates unjudged child',async()=>temporary(async dir=>{const {q}=await bench(dir,(b,input)=>input.prompt===PROMPTS.revise?{before:b.claim.text,after:'The study reports an association.',reason:'Remove causal claim',sourceIds:[id]}:{verdict:'unsupported',reason:'Correlation is not causation',evidence:[{documentId:id,page:b.sources[0].page,quote:b.sources[0].text}]});await q.draft('Treatment causes improvement.\nUnchanged text.');const d=q.drafts[0];await q.create({type:'verify',draftId:d.draftId,claimId:d.claims[0].id,sources:[source]});await settle(q);await q.create({type:'revise',checkId:q.jobs[0].jobId,claimId:d.claims[0].id});await settle(q);const j=q.jobs[1];await q.accept({jobId:j.jobId,selected:[j.proposals[0].id]});assert.equal(q.drafts[0].text,'Treatment causes improvement.\nUnchanged text.');assert.equal(q.drafts[1].text,'The study reports an association.\nUnchanged text.');assert.equal(q.drafts[1].verificationStatus,'unjudged');assert.equal(q.drafts[1].parentId,d.draftId);}));
test('missing textual source is unclear without model calls',async()=>temporary(async dir=>{const {q,ai}=await bench(dir,()=>({}));await q.create({type:'verify',claim:'Unknown',role:'user',sources:[{...source,pages:[{page:1,text:''}]}]});assert.equal(q.jobs[0].results[0].verdict,'unclear');assert.equal(ai.calls.length,0);}));
test('matrix versions have exact sources, independent Results/Discussion and survive restore',async()=>temporary(async dir=>{const {q}=await bench(dir,()=>({items:[]}));const row={value:'Association',page:1,quote:pages[0].text,certainty:'extracted'},group={status:'reported',rows:[row]},empty={status:'notApplicable',reason:'Conceptual',rows:[]};q.readings.jobs=[{...source,versionId:'version-1',state:'completed',created:1,result:{imrad:{sections:{results:group,discussion:{...group,rows:[{...row,value:'Interpretation'}]}},logic:{rq:group,theory:empty,constructs:empty,operationalization:empty,method:empty,contribution:empty,boundary:group}}}}];await q.matrix({projectId:'project',versions:['version-1']});const m=q.matrices[0];assert.equal(m.rows[0].cells.results.rows[0].value,'Association');assert.equal(m.rows[0].cells.discussion.rows[0].value,'Interpretation');assert.equal(m.rows[0].cells.method.status,'notApplicable');const raw=q.export();raw.readings={jobs:[]};assert.equal(q.prepare(raw).matrices.length,1);const bad=structuredClone(raw);bad.matrices[0].rows[0].cells.results.rows[0].quote='invented';assert.throws(()=>q.prepare(bad),/引文/);await q.create({type:'gap',matrixId:m.matrixId});await settle(q);assert.equal(q.jobs[0].state,'completed');assert.equal(q.jobs[0].studyBackground,null);}));
test('restoring forged support cannot overwrite computed verdict or source scope',async()=>temporary(async dir=>{const {q}=await bench(dir,b=>({verdict:'unsupported',reason:'Contradicts',evidence:[{documentId:id,page:b.sources[0].page,quote:b.sources[0].text}]}));await q.create({type:'verify',claim:'Causal claim',role:'ai',sources:[source]});await settle(q);const raw=structuredClone(q.export());raw.jobs[0].results[0].verdict='supported';assert.equal(q.prepare(raw).jobs[0].results[0].verdict,'unsupported');raw.jobs[0].batches.pop();raw.jobs[0].done--;raw.jobs[0].parts.pop();assert.throws(()=>q.prepare(raw),/覆蓋/);}));
test('background must be confirmed and hash cannot be changed on restore',async()=>temporary(async dir=>{const {q}=await bench(dir,b=>({verdict:'unclear',reason:'Insufficient',evidence:[]}));const background={id:'study',name:'Study',text:'My research question.',confirmed:true,confirmedAt:100};await assert.rejects(()=>q.create({type:'verify',claim:'x',role:'user',sources:[source],studyBackground:{...background,confirmed:false}}),/確認/);await q.create({type:'verify',claim:'x',role:'user',sources:[source],studyBackground:background});await settle(q);const raw=structuredClone(q.export());raw.jobs[0].studyBackground.text='Changed question';assert.throws(()=>q.prepare(raw),/背景快照/);}));
test('new citation markers cannot be introduced by a revision proposal',async()=>temporary(async dir=>{const {q}=await bench(dir,()=>({}));const job={claims:[{text:'Original.'}],sources:[source]};assert.throws(()=>q.validateRevision({before:'Original.',after:'New [cite:NEW].',reason:'fixture',sourceIds:[id]},job),/引用/);assert.throws(()=>q.validateRevision({before:'Original.',after:'Changed.',reason:'fixture',sourceIds:['b'.repeat(64)]},job),/來源/);}));
test('cancellation retains progress without publishing a support decision',async()=>temporary(async dir=>{let release;const {q}=await bench(dir,async b=>{await new Promise(r=>release=r);return {verdict:'supported',reason:'fixture',evidence:[{documentId:id,page:b.sources[0].page,quote:b.sources[0].text}]};});await q.create({type:'verify',claim:'Association',role:'author',sources:[source]});for(let i=0;i<100&&!release;i++)await new Promise(r=>setTimeout(r,2));await q.cancel(q.jobs[0].jobId);release();await settle(q);assert.equal(q.jobs[0].state,'cancelled');assert.equal(q.jobs[0].results.length,0);assert.equal(M.coverage(q.jobs[0]).unjudged,1);}));
test('semantic metrics distinguish execution failures from completed judgments',()=>{const {metrics}=require('./semantic-eval.cjs');const gold=[{caseId:'1',expected:'supported'},{caseId:'2',expected:'unsupported'}];const result=metrics(gold,[{caseId:'1',state:'failed'},{caseId:'2',state:'completed',verdict:'supported'}]);assert.equal(result.unjudged,1);assert.equal(result.falseSupport,1);assert.equal(result.supportPrecision,0);assert.equal(result.supportRecall,null);});

test('semantic usage sums real normalized CLI tokens without adding cache twice',()=>{const {metrics}=require('./semantic-eval.cjs');const r=metrics([{caseId:'1',expected:'supported'}],[{caseId:'1',state:'completed',verdict:'supported',usage:{input:100,output:20,total:120,cached:80}}]);assert.equal(r.reportedTotalTokens,120);assert.equal(r.missingUsage,0);});
