'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),model=require('../ebook-browser/mindmap-model.js'),usage=require('../ebook-browser/usage-ui.js');
const source=(id,certainty='extracted')=>({documentId:id,page:2,quote:'Research evidence.',certainty});
function fixture(){const id='a'.repeat(64),doc={id,title:'數位公共治理中跨部門資料協作與公民參與的研究架構：一份用於佈局驗證的合成文獻'},nodes=Array.from({length:45},(_,i)=>({id:'node:'+i,type:['concept','theory','method','finding','unknown'][i%5],name:'跨部門研究參與者如何在資訊不對稱與組織規範限制下協調資料共享及公共治理責任的長繁體中文研究內容第'+i+'項',sources:[source(id,i%3===0?'inferred':'extracted')]}));return {id,doc,graph:{nodes,edges:[{source:'node:3',target:'node:0',relation:'不能假設為階層',sources:[source(id)]}]}};}
function noOverlap(layout){for(let i=0;i<layout.nodes.length;i++)for(let j=i+1;j<layout.nodes.length;j++){const a=layout.nodes[i],b=layout.nodes[j];assert.ok(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y,a.id+' overlaps '+b.id);}for(const line of layout.edges)for(const node of layout.nodes.filter(n=>n.id!==line.parent&&n.id!==line.child)){assert.ok(line.x2<=node.x||line.x1>=node.x+node.width||Math.max(line.y1,line.y2)<=node.y||Math.min(line.y1,line.y2)>=node.y+node.height,'reading connector crosses unrelated node');}}
test('projection groups only original fields/types and preserves evidence without inventing graph hierarchy',()=>{const {id,doc,graph}=fixture(),copy=JSON.stringify(graph),root=model.project([doc],{[id]:graph},{[id]:{questions:[{value:'如何協調？',page:2,quote:'Research evidence.'}]}});assert.equal(root.label,doc.title);assert.deepEqual(root.children.map(x=>x.label),['研究問題','理論與概念','研究方法','研究發現','其他／待確認']);assert.ok(!root.children.some(n=>n.label==='結論與限制'));const all=root.children.flatMap(n=>n.children);assert.equal(all.length,46);assert.ok(all.every(n=>n.children.length===0));assert.equal(all[0].sources[0].certainty,'ambiguous');assert.equal(JSON.stringify(graph),copy);assert.equal(all.find(n=>n.originalIds.includes('node:3')).sources[0].page,2);});
test('source-exact field and graph nodes are deduplicated without claiming paraphrase certainty',()=>{const {id,doc,graph}=fixture(),node=graph.nodes[0],root=model.project([doc],{[id]:graph},{[id]:{questions:[{value:node.name,page:2,quote:'Research evidence.'}]}});const all=root.children.flatMap(n=>n.children);assert.equal(all.length,45);assert.equal(all.find(n=>n.label===node.name).sources[0].certainty,'inferred');});
test('long CJK labels, unequal subtree sizes and cycles never overlap in full or collapsed layouts',()=>{const {id,doc,graph}=fixture(),root=model.project([doc],{[id]:graph});noOverlap(model.layout(root));for(const group of root.children)noOverlap(model.layout(root,{collapsed:new Set([group.id])}));const full=model.layout(root),collapsed=model.layout(root,{collapsed:new Set(root.children.map(n=>n.id))});assert.ok(full.height>collapsed.height);assert.equal(collapsed.nodes.length,1+root.children.length);assert.ok(full.nodes.filter(n=>n.kind==='content').every(n=>n.lines.length>2&&n.height>=n.lines.length*24+36));});
test('multiple document roots never lose document-specific evidence or mutate old data',()=>{const {id,doc,graph}=fixture(),other={id:'b'.repeat(64),title:'另一文件'},root=model.project([doc,other],{[id]:graph,[other.id]:{nodes:[{...graph.nodes[0],sources:[source(other.id)]}],edges:[]}});assert.equal(root.kind,'scope');assert.equal(root.children.length,2);noOverlap(model.layout(root));assert.equal(root.children[1].children[0].children[0].sources[0].documentId,other.id);assert.equal(model.project([doc],{}).children.length,0);});
test('reader background status reflects actual phase and completed chunks without estimates or token JSON',()=>{assert.equal(usage.backgroundStatus(null),'未分析');assert.equal(usage.backgroundStatus(null,{state:'waiting'}),'分析等待');assert.equal(usage.backgroundStatus({state:'running',execution:'waiting',done:1,totalChunks:3}),'分析等待');assert.equal(usage.backgroundStatus({state:'running',execution:'processing',phase:'extract',done:1,totalChunks:3}),'分析中 · 1/3 段');assert.equal(usage.backgroundStatus({state:'running',phase:'integrate',done:3,totalChunks:3}),'研究整合中');assert.equal(usage.backgroundStatus({state:'running',done:3,totalChunks:3}),'研究整合中');for(const [state,label]of [['waiting','分析等待'],['completed','分析完成'],['partial','部分完成'],['failed','分析失敗'],['cancelled','分析已取消']])assert.equal(usage.backgroundStatus({state}),label);});
