'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const {AiService}=require('./ai-service.cjs');
const {validateDocument,chunksFor}=require('./research-queue.cjs');
const ranges=require(require('node:fs').existsSync(path.join(__dirname,'reader/page-ranges.js'))?'./reader/page-ranges.js':'../ebook-browser/page-ranges.js');
function validateTask(input){const doc=validateDocument(input);if(typeof input.prompt!=='string'||!input.prompt.trim()||input.prompt.length>4000||!Array.isArray(input.selectedPages)||!input.selectedPages.length||input.selectedPages.length>doc.pages.length||input.selectedPages.some(p=>!Number.isInteger(p)||p<1||p>doc.pages.length))throw Error('研究指令或指定頁碼不正確');const selectedPages=ranges.parse(input.selectedPages.join(','),doc.pages.length);return {...doc,prompt:input.prompt.trim(),selectedPages};}
function covered(task){return [...new Set(task.chunks.slice(0,task.done).flatMap(c=>c.map(p=>p.page)))].filter(p=>!task.chunks.slice(task.done).some(c=>c.some(x=>x.page===p))).sort((a,b)=>a-b);}
class PageTasks{
 constructor(directory,{service,skills}={}){this.file=path.join(directory,'page-tasks.json');this.skills=skills;this.tasks=[];this.active=null;this.service=service||new AiService(directory);const settings=this.service.settings.bind(this.service);this.service.settings=async()=>({...await settings(),provider:'codex-cli'});this.writes=Promise.resolve();this.stopping=false;}
 async load(){try{this.tasks=JSON.parse(await fs.readFile(this.file,'utf8')).tasks||[];for(const t of this.tasks)if(['running','waiting'].includes(t.state)){t.state='interrupted';t.message='上次工作中斷，請按重試繼續；不自動重送';}}catch(e){if(e.code!=='ENOENT')await fs.rename(this.file,this.file+'.invalid-'+Date.now()).catch(()=>{});}return this.snapshot();}
 snapshot(){return this.tasks.map(({pages,chunks,...t})=>({...t,totalChunks:chunks.length,execution:this.active===t.taskId&&t.state==='running'?(this.service.job?'processing':'waiting'):null,coveredPages:covered({...t,chunks}),missingTextPages:t.selectedPages.filter(p=>!pages.some(x=>x.page===p&&x.text.trim())),characterCount:pages.reduce((n,p)=>n+p.text.length,0)}));}
 async save(){const data=JSON.stringify({tasks:this.tasks});this.writes=this.writes.catch(()=>{}).then(async()=>{await fs.mkdir(path.dirname(this.file),{recursive:true});await fs.writeFile(this.file+'.tmp',data);await fs.rename(this.file+'.tmp',this.file);});return this.writes;}
 async enqueue(input){const doc=validateTask(input),pages=doc.pages.filter(p=>doc.selectedPages.includes(p.page)),chunks=chunksFor(pages);const task={...doc,instructionSnapshot:this.skills?.capture('research','custom',doc.prompt,input.skillId)||null,pages,totalPages:doc.pages.length,chunks,taskId:crypto.randomUUID(),done:0,parts:[],usage:[],result:'',state:chunks.length?'waiting':'partial',message:chunks.length?'等待共用 CLI 排程':'選定頁面無文字層，未送出',version:2,knowledge:{schemaVersion:1,entities:[],relations:[],adapter:null},created:Date.now()};this.tasks.push(task);await this.save();this.kick();return this.snapshot();}
 prepareRestore(oldTasks){if(this.active)throw Error('請先取消並等待多頁研究停止');if(!Array.isArray(oldTasks)||oldTasks.length>10000)throw Error('多頁研究備份不正確');const seen=new Set();return oldTasks.map(old=>{if(!old||!Array.isArray(old.pages)||!Number.isInteger(old.totalPages)||old.totalPages<1||old.totalPages>10000||typeof old.taskId!=='string'||old.taskId.length>64||seen.has(old.taskId))throw Error('多頁研究備份格式不正確');seen.add(old.taskId);const restoredPages=Array.from({length:old.totalPages},(_,i)=>old.pages.find(p=>p.page===i+1)||{page:i+1,text:''}),doc=validateTask({...old,pages:restoredPages}),pages=doc.pages.filter(p=>doc.selectedPages.includes(p.page)),chunks=chunksFor(pages);if(!Number.isInteger(old.done)||old.done<0||old.done>chunks.length||!Array.isArray(old.parts)||old.parts.length!==old.done||old.parts.some(p=>!p||typeof p.text!=='string'||p.text.length>200000||!Array.isArray(p.pages)||p.pages.some(page=>!doc.selectedPages.includes(page)))||typeof old.result!=='string'||old.result.length>100000000)throw Error('多頁研究進度不正確');return {...doc,instructionSnapshot:require('./skill-manager.cjs').validateContext(old.instructionSnapshot),pages,totalPages:old.totalPages,chunks,taskId:old.taskId,done:old.done,parts:old.parts,usage:Array.isArray(old.usage)?old.usage:[],result:old.result,created:old.created||Date.now(),version:2,state:old.state==='completed'?'completed':old.state==='partial'?'partial':'interrupted',message:'從備份還原；需要手動繼續，不自動送出'};});}
 async restore(tasks){this.tasks=this.prepareRestore(tasks);await this.save();return this.snapshot();}
 async cancel(id){const t=this.tasks.find(t=>t.taskId===id);if(!t)throw Error('找不到研究工作');t.state='cancelled';t.message='已取消；已回報用量仍保留';if(this.active===id)this.service.cancel();await this.save();return this.snapshot();}
 async retry(id){const t=this.tasks.find(t=>t.taskId===id);if(!t||this.active===id)throw Error('工作不存在或仍在取消中');if(t.state==='completed')return this.snapshot();t.state=t.chunks.length?'waiting':'partial';await this.save();this.kick();return this.snapshot();}
 kick(){if(this.active||this.stopping)return;const t=this.tasks.find(t=>t.state==='waiting');if(t)this.process(t).catch(()=>{});}
 async request(task,text,phase){const response=await this.service.run({action:'custom',prompt:task.prompt,instructionSnapshot:task.instructionSnapshot,text:JSON.stringify({phase,source:text})});task.usage.push({phase,model:response.model,usage:response.usage??null,at:Date.now()});return response.text;}
 async forget(id){for(const t of this.tasks.filter(t=>t.id===id)){t.state='cancelled';if(this.active===t.taskId)this.service.cancel();}this.tasks=this.tasks.filter(t=>t.id!==id);await this.save();}
 async process(t){this.active=t.taskId;try{const check=await this.service.checkCli();if(!check.ok)throw Error('Codex CLI 未安裝或未登入；未改用 API');if(t.state==='cancelled')return;t.state='running';t.message='分段處理指定頁面';await this.save();while(t.done<t.chunks.length){if(t.state==='cancelled'||this.stopping)return;const chunk=t.chunks[t.done];const answer=await this.request(t,chunk,'read');t.parts.push({pages:[...new Set(chunk.map(p=>p.page))],text:answer});t.done++;t.result=t.parts.map(p=>'PDF 實體頁 '+p.pages.join(',')+'\n'+p.text).join('\n\n');await this.save();}
  let level=t.parts.map(p=>({page:p.pages[0],text:'Original physical source pages: '+p.pages.join(',')+'\n'+p.text})),round=0,integrated=true;
  while(level.length>1||JSON.stringify(level).length>13000){if(t.state==='cancelled'||this.stopping)return;const groups=chunksFor(level);if(round>=8){integrated=false;break;}const next=[];for(const group of groups){if(t.state==='cancelled'||this.stopping)return;next.push({page:group[0].page,text:await this.request(t,group,'integrate')});await this.save();}if(next.length>=level.length&&JSON.stringify(next).length>=JSON.stringify(level).length&&round>0){integrated=false;break;}level=next;round++;}
  if(t.state==='cancelled'||this.stopping)return;if(integrated&&level.length)t.result=t.parts.length===1&&round===0?t.parts[0].text:level[0].text;const missing=t.pages.filter(p=>!p.text.trim()).length;t.state=missing||!integrated?'partial':'completed';t.message=!integrated?'指定文字已處理，但整合未收斂；保留全部分段結果':missing?`${missing} 頁無文字層；只處理可讀頁面，未做 OCR`:'指定頁面文字已完整分段處理並整合';t.completed=Date.now();await this.save();
 }catch(e){if(e.usage)t.usage.push({phase:'error',usage:e.usage,at:Date.now()});if(t.state!=='cancelled'){t.state='failed';t.message=e.message;}await this.save();}finally{this.active=null;this.kick();}}
 stop(){this.stopping=true;this.service.cancel();}
}
module.exports={PageTasks,validateTask,covered};
