'use strict';
const fs=require('node:fs/promises');
const path=require('node:path');
const PERMISSIONS=['documents.metadata.read','projects.read','notes.export','storage'];
function validateManifest(m){if(!m||!/^[a-z][a-z0-9-]{2,63}$/.test(m.id)||typeof m.name!=='string'||m.name.length>100||typeof m.version!=='string'||m.version.length>40||m.apiVersion!==1||typeof m.entry!=='string'||!/^[a-zA-Z0-9_-]+\.js$/.test(m.entry)||!Array.isArray(m.permissions)||m.permissions.some(p=>!PERMISSIONS.includes(p)))throw Error('外掛格式、API 版本或權限不相容');const commands=m.contributions?.commands||[],panels=m.contributions?.panels||[];if(!Array.isArray(commands)||commands.length>20||commands.some(c=>!c||typeof c.id!=='string'||!/^[a-z][a-z0-9-]{0,60}$/.test(c.id)||typeof c.title!=='string'||c.title.length>100))throw Error('外掛命令格式不正確');if(!Array.isArray(panels)||panels.length>20||panels.some(p=>!p||typeof p.id!=='string'||!/^[a-z][a-z0-9-]{0,60}$/.test(p.id)||typeof p.title!=='string'||p.title.length>100))throw Error('外掛面板格式不正確');return {id:m.id,name:m.name,version:m.version,apiVersion:1,entry:m.entry,permissions:[...new Set(m.permissions)],contributions:{commands,panels}};}
const SDK=`(()=>{let token,parentWindow;const pending=new Map(),commands=new Map(),events=new Map();let serial=0;const rpc=(method,args)=>new Promise((resolve,reject)=>{if(!token)return reject(Error('Host not ready'));const id=++serial;pending.set(id,{resolve,reject});parentWindow.postMessage({type:'plugin:rpc',token,id,method,args},'*');});window.CangjingPlugin=Object.freeze({apiVersion:1,getDocuments:()=>rpc('documents.metadata.read',null),getProjects:()=>rpc('projects.read',null),exportNotes:()=>rpc('notes.export',null),getData:()=>rpc('storage.get',null),setData:data=>rpc('storage.set',data),onCommand:(id,fn)=>{commands.set(id,fn);return()=>commands.delete(id);},onPanel:(id,fn)=>{commands.set('panel:'+id,fn);return()=>commands.delete('panel:'+id);},on:(name,fn)=>{events.set(name,fn);return()=>events.delete(name);}});addEventListener('message',async event=>{if(event.source!==parent)return;const m=event.data;if(!m||typeof m!=='object')return;if(m.type==='plugin:init'&&!token){token=m.token;parentWindow=event.source;parentWindow.postMessage({type:'plugin:ready',token},'*');}if(m.token!==token)return;if(m.type==='plugin:reply'){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(Error(m.error)):p.resolve(m.result);}}if(m.type==='plugin:command'){try{const fn=commands.get(m.command);if(!fn)throw Error('Command not found');const result=String(await fn(m.context));if(result.length>20000)throw Error('結果超過 20,000 字；請使用核心專案筆記匯出');parentWindow.postMessage({type:'plugin:result',token,id:m.id,result},'*');}catch(e){parentWindow.postMessage({type:'plugin:result',token,id:m.id,error:String(e.message).slice(0,1000)},'*');}}if(m.type==='plugin:event')try{events.get(m.name)?.();}catch{}});})();`;
class PluginHost{
 constructor(directory,bundled){this.root=path.join(directory,'plugins');this.config=path.join(directory,'plugins.json');this.bundled=bundled;this.plugins=[];this.dataWrites=Promise.resolve();}
 async init(){await fs.mkdir(this.root,{recursive:true});let config={};try{config=JSON.parse(await fs.readFile(this.config,'utf8'));}catch(e){if(e.code!=='ENOENT'){await fs.rename(this.config,this.config+'.invalid-'+Date.now()).catch(()=>{});config={};this.configError='設定損壞，外掛已停用；原檔另存保留';}}const folders=await fs.readdir(this.root,{withFileTypes:true});for(const folder of folders.filter(f=>f.isDirectory())){try{const m=validateManifest(JSON.parse(await fs.readFile(path.join(this.root,folder.name,'manifest.json'),'utf8')));if(m.id===folder.name)this.plugins.push({...m,enabled:config[m.id]===true});}catch{}}if(!this.plugins.some(p=>p.id==='document-info'))await this.install(this.bundled);return this.list();}
 list(){return this.plugins.map(p=>({...p,error:p.error||this.configError||null}));}
 async install(directory){const manifestFile=path.join(directory,'manifest.json');const stat=await fs.stat(manifestFile);if(stat.size>50000)throw Error('manifest 過大');const m=validateManifest(JSON.parse(await fs.readFile(manifestFile,'utf8')));if(this.plugins.some(p=>p.id===m.id))throw Error('已有同 ID 外掛，請先停用並手動移除本機版本');const entry=path.join(directory,m.entry),info=await fs.lstat(entry);if(!info.isFile()||info.isSymbolicLink()||info.size>1000000)throw Error('外掛入口必須是小於 1 MB 的一般 JavaScript 檔');const dest=path.join(this.root,m.id);await fs.mkdir(dest,{recursive:true});await fs.writeFile(path.join(dest,'manifest.json'),JSON.stringify(m));await fs.copyFile(entry,path.join(dest,m.entry));this.plugins.push({...m,enabled:false});await this.save();return this.list();}
 async save(){await fs.writeFile(this.config,JSON.stringify(Object.fromEntries(this.plugins.map(p=>[p.id,p.enabled]))));}
 plugin(id){if(typeof id!=='string')throw Error('Invalid plugin');const p=this.plugins.find(p=>p.id===id&&p.enabled);if(!p)throw Error('外掛未啟用');return p;}
 async enable(id,value){if(typeof value!=='boolean')throw Error('Invalid setting');const p=this.plugins.find(p=>p.id===id);if(!p)throw Error('找不到外掛');if(p.invalid)throw Error('外掛格式不相容，無法啟用');p.enabled=value;await this.save();return this.list();}
 authorize(id,method){const p=this.plugin(id);const permission=method.startsWith('storage.')?'storage':method;if(!['documents.metadata.read','projects.read','notes.export','storage.get','storage.set'].includes(method)||!p.permissions.includes(permission))throw Error('外掛沒有此權限');return p;}
 async rpc(id,method,args){const p=this.authorize(id,method);if(method==='storage.get'){try{return JSON.parse(await fs.readFile(path.join(this.root,p.id,'data.json'),'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw e;}}if(method==='storage.set'){const data=JSON.stringify(args);if(!data||data.length>1000000)throw Error('外掛資料超過 1 MB');this.dataWrites=this.dataWrites.catch(()=>{}).then(()=>fs.writeFile(path.join(this.root,p.id,'data.json'),data));await this.dataWrites;return true;}return {authorized:true};}
 async response(url){const parsed=new URL(url),p=this.plugin(parsed.hostname);const headers={'Content-Security-Policy':"default-src 'none'; script-src cangjing-plugin:; style-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'",'Access-Control-Allow-Origin':'*'};if(parsed.pathname==='/index.html')return new Response(`<!doctype html><html><head><meta charset="utf-8"></head><body><script src="sdk.js"></script><script src="${p.entry}"></script></body></html>`,{headers:{...headers,'Content-Type':'text/html'}});if(parsed.pathname==='/sdk.js')return new Response(SDK,{headers:{...headers,'Content-Type':'text/javascript'}});if(parsed.pathname==='/'+p.entry)return new Response(await fs.readFile(path.join(this.root,p.id,p.entry)),{headers:{...headers,'Content-Type':'text/javascript'}});return new Response('Not found',{status:404});}
}
module.exports={PluginHost,validateManifest};
