const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const os=require('node:os');
const {ResearchQueue,validateDocument,chunksFor,parseResult}=require('./research-queue.cjs');
const {PluginHost,validateManifest}=require('./plugin-host.cjs');
const organization=require('../ebook-browser/organization.js');
const id='a'.repeat(64),wait=ms=>new Promise(r=>setTimeout(r,ms));
async function temp(fn){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cangjing-test-'));try{await fn(dir);}finally{assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep));await fs.rm(dir,{recursive:true,force:true});}}
async function settled(q){for(let i=0;i<300;i++){if(!q.active&&q.jobs.every(j=>j.state!=='running'))return;await wait(10);}throw Error('queue timeout');}
function mock(){return {calls:[],settings:async()=>({provider:'openai-api'}),checkCli:async()=>({ok:true}),cancel(){if(this.inRun)this.cancelled=true;return this.inRun;},async run(input){this.inRun=true;this.calls.push(input);assert.equal((await this.settings()).provider,'codex-cli');const data=JSON.parse(input.text);if(this.delay)await wait(this.delay);this.inRun=false;if(this.cancelled){this.cancelled=false;throw Error('已取消');}const p=data.pages?.[0]||{page:1,text:'evidence'};return {text:JSON.stringify({summary:[{value:'研究摘要',page:p.page,quote:p.text.slice(0,20)}]}),usage:{inputTokens:20,outputTokens:10,totalTokens:30},model:'test'};}};}
test('page chunks preserve every character and physical page without truncation',()=>{const pages=[{page:1,text:'x'.repeat(40000)},{page:2,text:''},{page:3,text:'有效證據'}];const chunks=chunksFor(pages);assert.ok(chunks.length>2);assert.equal(chunks.flat().filter(p=>p.page===1).map(p=>p.text).join(''),pages[0].text);assert.equal(chunks.flat().at(-1).page,3);assert.ok(chunks.every(c=>JSON.stringify({phase:'extract',pages:c}).length<20000));assert.throws(()=>validateDocument({id,title:'x',pages:[{page:2,text:'bad'}]}));});
test('unverifiable source evidence is rejected and unknown metadata stays empty',()=>{const parsed=parseResult(JSON.stringify({doi:[{value:'invented',page:1,quote:'absent'}],summary:[{value:'ok',page:1,quote:'evidence'}]}),[{page:1,text:'evidence'}]);assert.deepEqual(parsed.doi,[]);assert.equal(parsed.summary.length,1);assert.throws(()=>parseResult('not json',[]));});
test('queue forces CLI, deduplicates, records coverage/usage and scanned pages',()=>temp(async dir=>{const service=mock(),q=new ResearchQueue(dir,{service});await q.load();await q.configure(true);const doc={id,title:'test',pages:[{page:1,text:'evidence'},{page:2,text:''}]};await q.enqueue(doc);await q.enqueue(doc);await settled(q);assert.equal(q.jobs.length,1);assert.equal(service.calls.length,1);assert.equal(q.jobs[0].state,'partial');assert.deepEqual(q.snapshot().jobs[0].processedPages,[1]);assert.equal(q.jobs[0].usage[0].usage.totalTokens,30);assert.equal(q.snapshot().jobs[0].pages,undefined);q.stop();}));
test('unavailable CLI does not invoke API or consume analysis calls',()=>temp(async dir=>{const service=mock();service.checkCli=async()=>({ok:false});const q=new ResearchQueue(dir,{service});await q.load();await q.configure(true);await q.enqueue({id,title:'test',pages:[{page:1,text:'evidence'}]});await settled(q);assert.equal(service.calls.length,0);assert.equal(q.jobs[0].state,'waiting');q.stop();}));
test('cancellation and retry preserve completed chunks; restart restores interrupted state',()=>temp(async dir=>{const service=mock(),q=new ResearchQueue(dir,{service});await q.load();await q.configure(true);service.delay=30;await q.enqueue({id,title:'long',pages:[{page:1,text:'evidence'.repeat(5000)}]});for(let i=0;i<100&&q.jobs[0].done<1;i++)await wait(10);await q.cancel(id);await settled(q);const done=q.jobs[0].done;assert.ok(done>=1);assert.equal(q.jobs[0].state,'cancelled');service.delay=0;await q.retry(id);await wait(20);await settled(q);assert.equal(q.jobs[0].done,q.jobs[0].chunks.length);assert.equal(q.jobs[0].state,'completed');q.enabled=false;q.jobs[0].state='running';await q.save();q.stop();const restored=new ResearchQueue(dir,{service:mock()});await restored.load();assert.equal(restored.jobs[0].state,'waiting');assert.equal(restored.jobs[0].done,q.jobs[0].done);assert.equal(restored.enabled,false);restored.stop();}));
test('multi-project membership shares one document and deleting a project preserves other links',()=>{const documents=[{id:'doc',data:'one original'}];let links={};links=organization.add(links,'doc','A');links=organization.add(links,'doc','B');links=organization.add(links,'doc','A');assert.deepEqual(links.doc,['A','B']);links=organization.deleteProject(links,'A');assert.deepEqual(links.doc,['B']);assert.equal(documents.length,1);assert.equal(documents[0].data,'one original');assert.deepEqual(organization.remove(links,'doc','B').doc,[]);});
test('plugin manifest enforces version, local entry and supported permissions',()=>{const good={id:'demo-plugin',name:'demo',version:'1',apiVersion:1,entry:'main.js',permissions:['storage'],contributions:{commands:[{id:'demo',title:'Demo'}]}};assert.equal(validateManifest(good).id,'demo-plugin');for(const bad of [{entry:'../escape.js'},{apiVersion:2},{permissions:['ai','filesystem']},{id:'../bad'}])assert.throws(()=>validateManifest({...good,...bad}));});
test('plugin broker rejects disabled/undeclared capabilities and namespaces storage',()=>temp(async dir=>{const host=new PluginHost(dir,path.join(__dirname,'../plugins/document-info'));await host.init();await assert.rejects(host.rpc('document-info','documents.metadata.read'));await host.enable('document-info',true);assert.deepEqual(await host.rpc('document-info','documents.metadata.read'),{authorized:true});await assert.rejects(host.rpc('document-info','storage.set',{bad:true}));await assert.rejects(host.rpc('document-info','ai.run'));const html=await host.response('cangjing-plugin://document-info/index.html');assert.ok(html.headers.get('Content-Security-Policy').includes("connect-src 'none'"));await host.enable('document-info',false);await assert.rejects(host.response('cangjing-plugin://document-info/entry.js'));}));
test('corrupted plugin settings do not prevent the library from starting',()=>temp(async dir=>{await fs.writeFile(path.join(dir,'plugins.json'),'broken json');const host=new PluginHost(dir,path.join(__dirname,'../plugins/document-info'));const list=await host.init();assert.equal(list[0].enabled,false);assert.ok(list[0].error);assert.ok((await fs.readdir(dir)).some(f=>f.startsWith('plugins.json.invalid-')));}));
test('corrupted analysis queue is preserved and disabled without breaking reading',()=>temp(async dir=>{await fs.writeFile(path.join(dir,'research-queue.json'),'broken json');const q=new ResearchQueue(dir,{service:mock()});const state=await q.load();assert.equal(state.enabled,false);assert.equal(state.jobs.length,0);assert.ok(state.error);assert.ok((await fs.readdir(dir)).some(f=>f.startsWith('research-queue.json.invalid-')));q.stop();}));
test('chunk boundaries preserve supplementary Unicode characters',()=>{const text='x'.repeat(11999)+'𠮷'+'研究';const chunks=chunksFor([{page:1,text}]);assert.equal(chunks.flat().map(p=>p.text).join(''),text);assert.ok(chunks.flat().every(p=>!/[\uD800-\uDBFF]$/.test(p.text)));});
test('restored analysis keeps progress but cannot auto-send until consent is enabled',()=>temp(async dir=>{const q=new ResearchQueue(dir,{service:mock()});await q.load();await q.enqueue({id,title:'test',pages:[{page:1,text:'evidence'}]});await q.restore({jobs:q.jobs});assert.equal(q.enabled,false);assert.equal(q.jobs[0].state,'waiting');assert.equal(q.service.calls.length,0);await assert.rejects(q.restore({jobs:[{id,title:'bad',pages:[{page:1,text:'x'}],done:2,partialResults:[]}]}));q.stop();}));

test('same pre-read request returns evidence architecture without another AI request',async()=>{const schema=require('../ebook-browser/knowledge-schema.js');const d=await fs.mkdtemp(path.join(os.tmpdir(),'cangjing-architecture-'));try{let calls=0;const s={settings:async()=>({}),checkCli:async()=>({ok:true}),cancel(){},run:async()=>{calls++;return {text:JSON.stringify({summary:[{value:'Synthetic understanding',page:1,quote:'Evidence'}],architecture:{nodes:[{key:'a',name:'Question',type:'concept',page:1,quote:'Evidence',certainty:'extracted'},{key:'b',name:'Method',type:'method',page:1,quote:'Evidence',certainty:'inferred'}],edges:[{source:'a',target:'b',relation:'investigated with',page:1,quote:'Evidence',certainty:'inferred'},{source:'a',target:'b',relation:'unsupported',page:1,quote:'fabricated',certainty:'extracted'}]}}),usage:null};}};const q=new ResearchQueue(d,{service:s});await q.configure(true);await q.enqueue({id:'e'.repeat(64),title:'Synthetic',pages:[{page:1,text:'Evidence'}]});for(let i=0;i<100&&q.active;i++)await new Promise(r=>setTimeout(r,5));const j=q.jobs[0];assert.equal(calls,1);assert.equal(j.result.summary.length,1);assert.equal(j.result.architecture.nodes.length,2);assert.equal(j.result.architecture.edges.length,1);assert.equal(j.result.architecture.rejected,1);await q.restore({jobs:q.jobs});assert.equal(q.jobs[0].result.architecture.edges[0].sources[0].certainty,'inferred');q.stop();}finally{assert.ok(d.startsWith(os.tmpdir()+path.sep));await fs.rm(d,{recursive:true,force:true});}});
