const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {SkillManager,parseBundle,folderBundle,zipBundle,validateContext}=require('./skill-manager.cjs');
const {validate,instructionsFor,argsFor}=require('./ai-service.cjs'),{PageTasks}=require('./page-tasks.cjs'),{KnowledgeQueue}=require('./knowledge-queue.cjs'),{ResearchQueue}=require('./research-queue.cjs');
const JSZip=require('../ebook-browser/vendor/jszip.min.js'),bundled=path.join(__dirname,'../research-skills'),id='d'.repeat(64);
const fixture={ 'SKILL.md':'---\nname: synthetic-review\ndescription: Review supplied synthetic evidence.\nversion: "2.0"\n---\nUse [criteria](references/criteria.md). Keep physical page evidence.\n','references/criteria.md':'Synthetic criterion: distinguish author statements and inference.'};
async function temp(fn){const root=await fs.mkdtemp(path.join(os.tmpdir(),'cangjing-skills-'));try{await fn(root);}finally{assert.ok(root.startsWith(os.tmpdir()+path.sep));await fs.rm(root,{recursive:true,force:true});}}
async function manager(root){const m=new SkillManager(root,bundled);await m.init();return m;}
async function zip(files=fixture,options={}){const z=new JSZip();for(const [name,value]of Object.entries(files))z.file(name,value);return z.generateAsync({type:'nodebuffer',compression:'DEFLATE',...options});}
async function settled(q){for(let i=0;i<300;i++){if(!q.active)return;await new Promise(r=>setTimeout(r,5));}throw Error('Worker timeout');}
function service(mode){return {calls:[],settings:async()=>({}),checkCli:async()=>({ok:true}),cancel(){},async run(input){validate(input);this.calls.push(input);const source=JSON.parse(input.text),p=(source.pages||source.source)[0];if(mode==='graph')return {text:JSON.stringify({nodes:[{key:'m',name:'Synthetic method',type:'method',page:p.page,quote:p.text.slice(0,20),certainty:'extracted'}],edges:[]}),usage:{input:20,output:5,total:25}};if(mode==='research')return {text:JSON.stringify({summary:[{value:'Synthetic summary',page:p.page,quote:p.text.slice(0,20)}]}),usage:{input:20,output:5,total:25}};return {text:'Synthetic results with physical page '+p.page,usage:{input:20,output:5,total:25}};}};}
test('built-in skills have valid entrypoints and independent defaults',()=>temp(async root=>{const m=await manager(root);assert.equal(m.status().skills.length,4);assert.equal(m.status().defaults.knowledge,'traceable-knowledge');assert.equal(m.status().defaults.research,'literature-evidence');for(const s of m.status().skills)assert.equal(parseBundle(s.files).name,s.name);}));
test('folder and ZIP import include controlled text references, disabled until enabled',()=>temp(async root=>{const dir=path.join(root,'fixture');await fs.mkdir(path.join(dir,'references'),{recursive:true});for(const [n,v]of Object.entries(fixture))await fs.writeFile(path.join(dir,n),v);assert.equal((await folderBundle(dir)).name,'synthetic-review');const m=await manager(root);await m.install(await zip());const s=m.status().skills.find(s=>s.name==='synthetic-review');assert.equal(s.enabled,false);assert.equal(s.source,'使用者匯入');assert.throws(()=>m.capture('research','custom','Review','synthetic-review'),/停用/);await m.change({id:s.name,enabled:true});assert.equal(m.capture('research','custom','Review',s.name).version,'2.0');await assert.rejects(m.install(dir),/同名/);}));
test('single top-level folder ZIP is supported without importing sibling content',async()=>{const files=Object.fromEntries(Object.entries(fixture).map(([n,v])=>['synthetic-review/'+n,v]));assert.equal((await zipBundle(await zip(files))).contentHash,parseBundle(fixture).contentHash);await assert.rejects(zipBundle(await zip({...files,'sibling/SKILL.md':fixture['SKILL.md']})));});
test('ZIP rejects traversal, absolute paths, backslashes, executable resources and symlinks',async()=>{for(const name of ['../escape.md','/escape.md','C:/escape.md','references/../escape.md','references\\escape.md','scripts/run.sh','hooks/hook.md','references/con.txt'])await assert.rejects(zipBundle(await zip({...fixture,[name]:'Synthetic'})));const z=new JSZip();z.file('SKILL.md',fixture['SKILL.md']);z.file('references/link.md','target',{unixPermissions:0o120777});await assert.rejects(zipBundle(await z.generateAsync({type:'nodebuffer',platform:'UNIX'})),/符號連結/);});
test('ZIP detects case duplicates and bounded compression before importing',async()=>{await assert.rejects(zipBundle(await zip({...fixture,'skill.md':fixture['SKILL.md']})),/重複/);await assert.rejects(zipBundle(await zip({...fixture,'references/large.md':'x'.repeat(65537)})),/過大/);const files={...fixture};for(let i=0;i<22;i++)files['references/'+i+'.txt']='x';await assert.rejects(zipBundle(await zip(files)));});
test('invalid UTF-8, binary references and unsafe YAML fail without evaluation',async()=>{await assert.rejects(zipBundle(await zip({...fixture,'references/invalid.txt':Buffer.from([255])})),/UTF-8/);assert.throws(()=>parseBundle({...fixture,'references/binary.txt':'\0'}),/二進位/);for(const front of ['name: !!js/function "function(){}"\ndescription: Unsafe','name: &n synthetic-review\ndescription: *n','name: synthetic-review\nname: repeated\ndescription: duplicated','name: Synthetic Review\ndescription: invalid','name: synthetic-review\ndescription: [not,a,string]'])assert.throws(()=>parseBundle({'SKILL.md':'---\n'+front+'\n---\nReview.'}));});
test('folder rejects unsupported files and size limits',()=>temp(async root=>{await fs.writeFile(path.join(root,'SKILL.md'),fixture['SKILL.md']);await fs.writeFile(path.join(root,'run.js'),'synthetic');await assert.rejects(folderBundle(root),/只支援/);await fs.unlink(path.join(root,'run.js'));await fs.writeFile(path.join(root,'SKILL.md'),'x'.repeat(65537));await assert.rejects(folderBundle(root),/64 KB/);}));
test('instruction order, source boundary and CLI isolation remain explicit',()=>temp(async root=>{const m=await manager(root);await m.install(await zip());await m.change({id:'synthetic-review',enabled:true});await m.change({agents:'COMMON-SYNTHETIC-RULE'});const snapshot=m.capture('research','custom','USER-SYNTHETIC-PROMPT','synthetic-review');const v=snapshot.instructions;assert.ok(v.indexOf('Do not use tools')<v.indexOf('USER-SYNTHETIC-PROMPT'));assert.ok(v.indexOf('USER-SYNTHETIC-PROMPT')<v.indexOf('COMMON-SYNTHETIC-RULE'));assert.ok(v.indexOf('COMMON-SYNTHETIC-RULE')<v.indexOf('Synthetic criterion'));assert.match(v,/not native skill discovery/);validate({action:'custom',prompt:'USER-SYNTHETIC-PROMPT',text:'Source evidence',instructionSnapshot:snapshot});assert.throws(()=>validate({action:'custom',prompt:'changed',text:'Source',instructionSnapshot:snapshot}),/快照不符/);const args=argsFor('temporary','output');assert.ok(args.includes('--ignore-user-config'));assert.ok(args.includes('skip_host_skill_discovery'));assert.ok(args.includes('shell_tool'));assert.ok(args.includes('hooks'));assert.ok(args.includes('project_doc_max_bytes=0'));assert.match(instructionsFor({action:'research'}),/Unknown fields must be empty arrays/);}));
test('settings persist, defaults can be disabled, built-ins restored and users deleted',()=>temp(async root=>{const m=await manager(root);await m.install(await zip());await m.change({id:'synthetic-review',enabled:true});await m.change({defaults:{research:'synthetic-review',knowledge:''},agents:'Synthetic shared rules'});const next=await manager(root);assert.equal(next.status().agents,'Synthetic shared rules');assert.equal(next.capture('research','research').skillId,'synthetic-review');await next.change({id:'synthetic-review',enabled:false});assert.equal(next.status().defaults.research,'');await next.change({restoreDefaults:true});assert.equal(next.status().skills.length,5);assert.equal(next.status().defaults.research,'literature-evidence');await next.change({id:'synthetic-review',remove:true});assert.equal(next.status().skills.length,4);await assert.rejects(next.change({id:'literature-evidence',remove:true}));}));
test('malformed settings preserved and recover to validated defaults',()=>temp(async root=>{await fs.writeFile(path.join(root,'research-skills.json'),JSON.stringify({agents:'x',skills:[{files:{}}]}));const m=await manager(root);assert.match(m.status().error,/無法驗證/);assert.equal(m.status().skills.length,4);assert.ok((await fs.readdir(root)).some(n=>n.includes('.invalid-')));}));
test('immutable snapshots preserve references and reject tampering on backup',()=>temp(async root=>{const m=await manager(root),snapshot=m.capture('research','custom','Synthetic prompt');const old=JSON.stringify(snapshot);await m.change({agents:'Changed rules'});assert.equal(JSON.stringify(snapshot),old);assert.notEqual(m.capture('research','custom','Synthetic prompt').profileHash,snapshot.profileHash);assert.equal(validateContext(snapshot).contentHash,snapshot.contentHash);assert.throws(()=>validateContext({...snapshot,agents:'tampered'}),/快照/);const bundle=m.prepareRestore(JSON.parse(JSON.stringify(m.status())));assert.equal(bundle.agents,'Changed rules');assert.throws(()=>m.prepareRestore({...bundle,agents:''}));}));
test('multi-chunk and integration use identical snapshot; cancelled retry uses old rules',()=>temp(async root=>{const m=await manager(root),s=service(),q=new PageTasks(root,{service:s,skills:m});await q.load();await q.enqueue({id,title:'Synthetic',pages:[{page:1,text:'Synthetic evidence '.repeat(1800)},{page:2,text:'More synthetic evidence'}],selectedPages:[1,2],prompt:'Compare evidence',skillId:'methods-review'});await settled(q);assert.ok(s.calls.length>1);const snapshot=q.tasks[0].instructionSnapshot;assert.ok(s.calls.every(c=>c.instructionSnapshot.profileHash===snapshot.profileHash));await m.change({agents:'New setting',id:'methods-review',enabled:false});q.tasks[0].state='cancelled';q.tasks[0].done=0;q.tasks[0].parts=[];await q.retry(q.tasks[0].taskId);await settled(q);assert.equal(q.tasks[0].instructionSnapshot.profileHash,snapshot.profileHash);const restored=q.prepareRestore(JSON.parse(JSON.stringify(q.tasks)));assert.deepEqual(restored[0].instructionSnapshot,snapshot);q.stop();}));
test('graph caches isolated across skill/rule versions while old usage/history remains',()=>temp(async root=>{const m=await manager(root),s=service('graph'),q=new KnowledgeQueue(root,{service:s,skills:m});await q.load();await q.configure(true);const input={id,title:'Synthetic',pages:[{page:1,text:'Synthetic source evidence'}]};await q.enqueue(input);await settled(q);const old=q.jobs[0].instructionSnapshot,count=s.calls.length;await m.change({agents:'New graph rules'});await q.retry(id);await settled(q);assert.equal(s.calls.length,count);assert.equal(q.jobs[0].instructionSnapshot.profileHash,old.profileHash);await q.enqueue({...input,replaceWithCurrent:true});await settled(q);assert.ok(s.calls.length>count);assert.equal(q.history.length,1);assert.equal(q.history[0].usage.length,1);assert.notEqual(q.jobs[0].instructionSnapshot.profileHash,old.profileHash);assert.deepEqual(q.prepareRestore(q.history)[0].instructionSnapshot,old);q.stop();}));
test('pre-read defaults produce separate histories without changing existing snapshots',()=>temp(async root=>{const m=await manager(root),s=service('research'),q=new ResearchQueue(root,{service:s,skills:m});await q.load();await q.configure(true);const doc={id,title:'Synthetic',pages:[{page:1,text:'Synthetic source evidence'}]};await q.enqueue(doc);await settled(q);const before=q.jobs[0].instructionSnapshot;await m.change({defaults:{research:'methods-review',knowledge:''}});await q.enqueue(doc);assert.equal(q.jobs[0].instructionSnapshot.profileHash,before.profileHash);await q.enqueue({...doc,replaceWithCurrent:true});await settled(q);assert.equal(q.history.length,1);assert.equal(q.jobs[0].instructionSnapshot.skillId,'methods-review');await q.restore({jobs:q.jobs,researchHistory:q.history});assert.equal(q.enabled,false);assert.equal(q.history.length,1);assert.equal(q.history[0].instructionSnapshot.profileHash,before.profileHash);q.stop();}));

test('common rules have a single canonical local AGENTS.md file',()=>temp(async root=>{const m=await manager(root);await m.change({agents:'Canonical synthetic rules'});assert.equal(await fs.readFile(path.join(root,'AGENTS.md'),'utf8'),'Canonical synthetic rules');const settings=JSON.parse(await fs.readFile(path.join(root,'research-skills.json'),'utf8'));assert.equal(settings.agents,undefined);await fs.writeFile(path.join(root,'AGENTS.md'),'Manually edited synthetic rules');const n=await manager(root);assert.equal(n.status().agents,'Manually edited synthetic rules');}));
test('forged ZIP expansion sizes cannot bypass streamed size bounds',async()=>{const bytes=await zip({...fixture,'references/bomb.txt':'x'.repeat(300000)});const b=Buffer.from(bytes);for(let i=0;i<b.length-46;i++)if(b.readUInt32LE(i)===0x02014b50&&b.readUInt32LE(i+24)>65536)b.writeUInt32LE(1,i+24);await assert.rejects(zipBundle(b),/解壓|64 KB/);});

test('no selected Skill retains original action with only shared research rules',()=>temp(async root=>{const m=await manager(root),snap=m.capture('research','custom','Synthetic user prompt','');assert.equal(snap.skillId,null);assert.equal(snap.contentHash,null);assert.equal(validateContext(snap).profileHash,snap.profileHash);validate({action:'custom',prompt:'Synthetic user prompt',text:'Synthetic source',instructionSnapshot:snap});}));
