const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {CliScheduler}=require('./cli-scheduler.cjs'),{PageTasks,validateTask}=require('./page-tasks.cjs'),{KnowledgeQueue}=require('./knowledge-queue.cjs');
const ranges=require('../ebook-browser/page-ranges.js'),schema=require('../ebook-browser/knowledge-schema.js');const id='b'.repeat(64),wait=ms=>new Promise(r=>setTimeout(r,ms));
async function temporary(fn){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'cangjing-workflow-'));try{await fn(directory);}finally{assert.ok(directory.startsWith(os.tmpdir()+path.sep));await fs.rm(directory,{recursive:true,force:true});}}
async function settled(q){for(let i=0;i<200;i++){if(!q.active)return;await wait(10);}throw Error('timeout');}
function service(){return {calls:[],settings:async()=>({provider:'openai-api'}),checkCli:async()=>({ok:true}),cancel(){this.cancelled=true;},async run(input){this.calls.push(input);assert.equal((await this.settings()).provider,'codex-cli');const data=JSON.parse(input.text);return {text:data.phase==='read'?'Compared evidence on PDF page '+data.source[0].page:'Integrated PDF pages 1 and 3',usage:{totalTokens:13},model:'fixture'};}};}
test('page range syntax validates bounds, sorts, deduplicates, and resolves current',()=>{assert.deepEqual(ranges.parse('1-3,3,7，10-12',12),[1,2,3,7,10,11,12]);assert.deepEqual(ranges.parse('current',5,3),[3]);assert.deepEqual(ranges.parse('all',3),[1,2,3]);for(const s of ['0','2-1','6','1,','a','1-2-3'])assert.throws(()=>ranges.parse(s,5));assert.throws(()=>validateTask({id,title:'t',pages:[{page:1,text:'x'}],selectedPages:[2],prompt:'x'}));});
test('shared scheduler serializes work, prioritizes waiting interactive tasks, cancels queued owner',async()=>{const q=new CliScheduler(),order=[];let release;const gate=new Promise(r=>release=r);const first=q.run('one',async()=>{order.push(1);await gate;order.push(2);});const background=q.run('two',()=>order.push(4),'background'),interactive=q.run('three',()=>order.push(3));const cancelled=q.run('four',()=>order.push(99));const rejected=assert.rejects(cancelled,/已取消/);assert.equal(q.cancel('four'),true);release();await Promise.all([first,background,interactive,rejected]);assert.deepEqual(order,[1,2,3,4]);});
test('multi-page research preserves all selected text and reports unreadable pages and original prompt',()=>temporary(async directory=>{const s=service(),q=new PageTasks(directory,{service:s});await q.load();const text='😀原頁證據'.repeat(6000);await q.enqueue({id,title:'Synthetic',pages:[{page:1,text},{page:2,text:''},{page:3,text:'page three evidence'},{page:4,text:'not selected'}],selectedPages:[3,1,2],prompt:'Compare methods; cite pages'});await settled(q);const task=q.snapshot()[0],calls=s.calls.filter(c=>JSON.parse(c.text).phase==='read').flatMap(c=>JSON.parse(c.text).source);assert.equal(calls.filter(p=>p.page===1).map(p=>p.text).join(''),text);assert.ok(calls.every(p=>p.page!==4));assert.deepEqual(task.coveredPages,[1,3]);assert.deepEqual(task.missingTextPages,[2]);assert.equal(task.state,'partial');assert.equal(task.prompt,'Compare methods; cite pages');assert.ok(task.usage.length>1);q.stop();}));
test('no CLI and scan-only page research never calls an API; restart requires manual retry',()=>temporary(async directory=>{const s=service();s.checkCli=async()=>({ok:false});const q=new PageTasks(directory,{service:s});await q.load();await q.enqueue({id,title:'test',pages:[{page:1,text:'source'}],selectedPages:[1],prompt:'compare'});await settled(q);assert.equal(q.snapshot()[0].state,'failed');assert.equal(s.calls.length,0);await q.enqueue({id,title:'scan',pages:[{page:1,text:''}],selectedPages:[1],prompt:'compare'});assert.equal(q.snapshot()[1].state,'partial');q.tasks[0].state='running';await q.save();q.stop();const next=new PageTasks(directory,{service:service()});await next.load();assert.equal(next.snapshot()[0].state,'interrupted');assert.equal(next.service.calls.length,0);next.stop();}));
const graph=(quote='Evidence')=>JSON.stringify({nodes:[{key:'a',name:'Method A',type:'method',page:1,quote,certainty:'extracted'},{key:'b',name:'Finding B',type:'finding',page:1,quote,certainty:'inferred'}],edges:[{source:'a',target:'b',relation:'supports',page:1,quote,certainty:'inferred'}]});
test('knowledge schema verifies every node and edge source and preserves certainty',()=>{const valid=schema.parse(graph(),id,[{page:1,text:'Evidence'}]);assert.equal(valid.nodes.length,2);assert.equal(valid.edges[0].sources[0].certainty,'inferred');const bad=schema.parse(graph('fabricated'),id,[{page:1,text:'Evidence'}]);assert.equal(bad.nodes.length,0);assert.equal(bad.edges.length,0);assert.equal(bad.rejected,3);const duplicate=schema.merge([valid,schema.parse(graph(),'c'.repeat(64),[{page:1,text:'Evidence'}])]);assert.equal(duplicate.nodes.length,2);assert.equal(duplicate.nodes[0].sources.length,2);assert.equal(duplicate.edges[0].sources.length,2);assert.throws(()=>schema.parse('not JSON',id,[]));});
test('knowledge opt-in is independent; originals processed completely and cached retries do not resend',()=>temporary(async directory=>{const s=service();s.run=async function(input){this.calls.push(input);const data=JSON.parse(input.text),p=data.pages[0];return {text:graph(p.text.slice(0,8)),usage:{totalTokens:14},model:'fixture'};};const q=new KnowledgeQueue(directory,{service:s});await q.load();await assert.rejects(q.enqueue({id,title:'t',pages:[{page:1,text:'Evidence'}]}));await q.configure(true);const text='Evidence '.repeat(3500);await q.enqueue({id,title:'t',pages:[{page:1,text}]});await settled(q);assert.equal(q.snapshot().jobs[0].state,'completed');assert.equal(s.calls.flatMap(c=>JSON.parse(c.text).pages).map(p=>p.text).join(''),text);const count=s.calls.length;await q.retry(id);await settled(q);assert.equal(s.calls.length,count);assert.ok(q.jobs[0].graph.nodes.length);q.stop();}));
test('new backups validate source evidence, preserve progress, and require fresh sending consent',()=>temporary(async directory=>{const s=service(),tasks=new PageTasks(directory,{service:s});await tasks.load();await tasks.enqueue({id,title:'test',pages:[{page:1,text:'Evidence'},{page:2,text:'other'}],selectedPages:[1],prompt:'Compare'});await settled(tasks);const backup=JSON.parse(JSON.stringify(tasks.tasks));await tasks.restore(backup);assert.equal(tasks.tasks[0].result,backup[0].result);tasks.tasks[0].state='running';const restored=tasks.prepareRestore(tasks.tasks);assert.equal(restored[0].state,'interrupted');assert.throws(()=>tasks.prepareRestore([{...backup[0],done:99}]));tasks.stop();const graphService=service();graphService.run=async()=>({text:graph(),usage:null,model:'fixture'});const knowledge=new KnowledgeQueue(directory,{service:graphService});await knowledge.load();await knowledge.configure(true);await knowledge.enqueue({id,title:'t',pages:[{page:1,text:'Evidence'}]});await settled(knowledge);const saved=JSON.parse(JSON.stringify(knowledge.jobs));await knowledge.restore(saved);assert.equal(knowledge.enabled,false);assert.equal(knowledge.jobs[0].graph.nodes.length,2);saved[0].graph.nodes[0].sources[0].quote='fake';assert.throws(()=>knowledge.prepareRestore(saved));knowledge.stop();}));
test('JSON-escaped source text stays below request limits without lost characters',()=>{const {chunksFor}=require('./research-queue.cjs');const text='"\\\n'.repeat(20000);const chunks=chunksFor([{page:1,text}]);assert.equal(chunks.flat().map(p=>p.text).join(''),text);assert.ok(chunks.every(chunk=>JSON.stringify({phase:'read',source:chunk}).length<20000));});
