'use strict';
const {app,BrowserWindow,dialog}=require('electron'),fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const calls=[],errors=[],checks=[];const profile=path.join(__dirname,'../work/.smoke-workbench-'+process.pid);const originalSetPath=app.setPath.bind(app);app.setPath=(key,value)=>originalSetPath(key,key==='userData'?profile:value);process.env.CANGJING_SMOKE='1';
dialog.showErrorBox=(title,message)=>console.error(title+': '+message);
dialog.showOpenDialog=async()=>({canceled:true,filePaths:[]});dialog.showMessageBox=async()=>({response:0});
const {AiService}=require('./ai-service.cjs'),{PROMPTS}=require('./evidence-workbench.cjs');
AiService.prototype.checkCli=async()=>({ok:true,model:'fixture'});
AiService.prototype.runDirect=async function(input){require('./ai-service.cjs').validate(input);calls.push(input);if(['translate','explain','summarize'].includes(input.action))return {text:'Synthetic research assistant response',model:'fixture',usage:{totalTokens:7},provider:'codex-cli'};const b=JSON.parse(input.text);let raw;if(input.action==='reading'){const page=b.pages?.find(p=>p.text.includes('association'))||{page:1,text:'The study reports an association.'};const row={value:'Reported association',page:page.page,quote:page.text.slice(0,300),certainty:'extracted'},group={status:'reported',rows:[row]};raw={summary:[row],imrad:{schemaVersion:1,sections:{introduction:group,methods:{status:'notApplicable',reason:'Conceptual fixture',rows:[]},results:group,discussion:{...group,rows:[{...row,value:'Author interpretation'}]}},logic:{rq:group,evidence:group,claim:group,boundary:group},strongest:b.phase==='imrad-integrate'?[{...row,stage:'evidence'}]:[],weakest:[],links:[],mapping:b.confirmedStudy?[{...row,value:'Possible bounded transfer',studyQuote:b.confirmedStudy.text.slice(0,100)}]:[]}};}
else if(input.prompt===PROMPTS.verify)raw={verdict:b.claim.text.includes('causes')?'unsupported':'supported',reason:'Synthetic fixture only: association cannot prove causation',evidence:[{documentId:b.sources[0].documentId,page:b.sources[0].page,quote:b.sources[0].text}]};
else if(input.prompt===PROMPTS.revise)raw={before:b.claim.text,after:'The study reports an association.',reason:'Remove causal overstatement',sourceIds:b.allowedSources};
else if(input.prompt===PROMPTS.gap){const rows=b.matrix.flatMap(r=>r.cell?.rows?.map(x=>({...x,documentId:r.documentId}))||Object.values(r.cells||{}).flatMap(c=>c.rows.map(x=>({...x,documentId:r.documentId}))));raw={items:rows.length?[{kind:'extension',value:'Candidate extension bounded by selected evidence',evidence:[{documentId:rows[0].documentId,page:rows[0].page,quote:rows[0].quote}],...(b.confirmedStudy?{studyQuote:b.confirmedStudy.text.slice(0,100)}:{})}]:[]};}
else return {text:'Synthetic research assistant response',model:'fixture',usage:{totalTokens:7},provider:'codex-cli'};
return {text:JSON.stringify(raw),model:'fixture',usage:{totalTokens:11},provider:'codex-cli'};};
app.on('web-contents-created',(_e,c)=>c.on('console-message',details=>{if(details.level==='error')errors.push(details.message);}));
require('./main.cjs');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const check=(name,value)=>{if(!value)throw Error(name);checks.push(name);};
function pdf(){const streams=['The study reports an association.','The sample is limited to one city.'];const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R 6 0 R] /Count 2 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];const content=s=>'BT /F1 16 Tf 60 740 Td ('+s+') Tj ET';let stream=content(streams[0]);objects.push('<< /Length '+stream.length+' >>\nstream\n'+stream+'\nendstream');objects.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 7 0 R >>');stream=content(streams[1]);objects.push('<< /Length '+stream.length+' >>\nstream\n'+stream+'\nendstream');let s='%PDF-1.4\n',offsets=[];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(s));s+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const start=Buffer.byteLength(s);s+='xref\n0 8\n0000000000 65535 f \n'+offsets.map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 8 /Root 1 0 R >>\nstartxref\n'+start+'\n%%EOF';return Buffer.from(s);}
app.whenReady().then(async()=>{try{let w;for(let i=0;i<100;i++){w=BrowserWindow.getAllWindows()[0];if(w&&!w.webContents.isLoading())break;await sleep(100);}await sleep(500);const wc=w.webContents;wc.debugger.attach('1.3');const run=js=>wc.executeJavaScript('(async()=>{'+js+'})()',true);const click=async selector=>{await run('document.querySelector('+JSON.stringify(selector)+').scrollIntoView({block:"center"});');const pos=await run('const r=document.querySelector('+JSON.stringify(selector)+').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};');await wc.debugger.sendCommand('Input.dispatchMouseEvent',{type:'mousePressed',...pos,button:'left',buttons:1,clickCount:1});await wc.debugger.sendCommand('Input.dispatchMouseEvent',{type:'mouseReleased',...pos,button:'left',buttons:0,clickCount:1});await sleep(100);};const button=async(label,scope='#evidence-workbench')=>{await run('document.querySelectorAll("#test-current-button").forEach(n=>n.removeAttribute("id"));const b=[...document.querySelectorAll('+JSON.stringify(scope+' button')+')].find(b=>b.textContent==='+JSON.stringify(label)+');if(!b)throw Error("Missing button: '+label+'");for(let n=b.parentElement;n;n=n.parentElement)if(n.tagName==="DETAILS")n.open=true;b.id="test-current-button";');await click('#test-current-button');};const waitJobs=async()=>{for(let i=0;i<100;i++){if(await run('const s=await desktopReader.workbenchStatus();return !s.jobs.some(j=>["waiting","running"].includes(j.state))&&!s.readings.jobs.some(j=>["waiting","running"].includes(j.state));'))return;await sleep(50);}throw Error('jobs timeout');};
check('startup does not call AI',calls.length===0);check('old AI entrances absent',await run('return !document.querySelector("#document-summary")&&!document.querySelector("#reader-analysis-status")&&!document.querySelector(".knowledge-dialog")&&!window.KnowledgeUI&&!window.SummaryUI;'));check('renderer isolated',await run('return typeof require==="undefined";'));
const bytes=pdf(),id=crypto.createHash('sha256').update(bytes).digest('hex'),base64=bytes.toString('base64');await run(`window.confirm=()=>true;const raw=Uint8Array.from(atob('${base64}'),c=>c.charCodeAt(0));await importFiles([new File([raw],'Synthetic-study.pdf',{type:'application/pdf'})]);`);await sleep(500);check('PDF import never auto analyzes',calls.length===0);check('PDF imported',await run('return records.length===1;'));
await run(`await ReaderData.put('organization',{id:'projects',projects:[{id:'project-test',name:'Evidence project',description:'Synthetic'}]});await ReaderData.put('organization',{id:'project-links',links:{'${id}':['project-test']}});`);await run('location.reload();');await sleep(1000);await run('window.confirm=()=>true;');check('reload never invokes AI',calls.length===0);
await button('證據研究工作台','.research-controls');check('manual workspace opens',await run('return !document.querySelector("#evidence-workbench").hidden;'));await button('分析所選文獻');await waitJobs();await run('await EvidenceWorkbenchUI.refresh();');check('full manual reading complete',await run('const j=(await desktopReader.workbenchStatus()).readings.jobs[0];return j.state==="completed"&&j.processedPages.length===2&&j.result.imrad.sections.results.rows.length>0;'));check('no graph generation prompt',calls.filter(c=>c.action==='reading').every(c=>!c.instructionSnapshot.instructions.includes('include architecture:')));
await button('證據比較');await run('const p=document.querySelector("[aria-label=研究專案]");p.value="project-test";p.dispatchEvent(new Event("change"));');check('project-specific version available',await run('return document.querySelector("[aria-label^=納入]")&&!document.querySelector("[aria-label^=納入]").disabled;'));await click('[aria-label^="納入"]');const before=calls.length;await button('建立選定版本的證據矩陣');await run('const p=document.querySelector("[aria-label=證據矩陣版本]");p.value=p.options[1].value;p.dispatchEvent(new Event("change"));');check('matrix uses existing analysis without AI',calls.length===before);check('distinct results and discussion columns',await run('return document.querySelector("table").textContent.includes("作者解釋")&&document.querySelector("table").textContent.includes("結果");'));await click('.evidence-table-scroll .evidence-statement');check('matrix reveals original evidence',await run('return document.querySelector(".evidence-source blockquote").textContent.includes("association");'));
await button('回到 PDF 原頁');check('source opens exact physical PDF page',await run('return currentMode==="pdf"&&webReader.index===0;'));await run('await EvidenceWorkbenchUI.open();');await button('研究缺口');await run('const p=document.querySelector("[aria-label=證據矩陣版本]");p.value=p.options[1].value;p.dispatchEvent(new Event("change"));');await button('分析選定文獻池的研究缺口');await waitJobs();await run('await EvidenceWorkbenchUI.refresh();');check('gap preserves missing background',await run('const j=(await desktopReader.workbenchStatus()).jobs.find(j=>j.type==="gap");return j.state==="completed"&&!j.studyBackground;'));
await button('草稿版本');await run('document.querySelector("[aria-label=草稿原文]").value="Treatment causes improvement.\\nUnchanged sentence.";');await button('保存新草稿版本');await button('選擇此版本進行查核');await click('[aria-label^="查核來源"]');await button('查核主張與選定來源');await waitJobs();await run('await EvidenceWorkbenchUI.refresh();');check('unsupported causal claim is visibly distinct',await run('return document.querySelector("#evidence-workbench").textContent.includes("不支持 · 查看理由與原文");'));await button('提出此句修訂');await waitJobs();await run('await EvidenceWorkbenchUI.refresh();');await click('[aria-label="接受此修訂"]');await button('保存勾選提案為新版本');check('accepted proposal preserves original and unflagged sentence',await run('const s=await desktopReader.workbenchStatus();return s.drafts.length===2&&s.drafts[0].text==="Treatment causes improvement.\\nUnchanged sentence."&&s.drafts[1].text==="The study reports an association.\\nUnchanged sentence."&&s.drafts[1].verificationStatus==="unjudged";'));
const backup=await run('const bytes=await CangjingBackup.encode();const state=await CangjingBackup.decode(bytes);return {size:bytes.length,workbench:state.research.workbench,skills:state.research.skills};');check('backup v6 includes workspace and skills',backup.size>100&&backup.workbench.jobs.length===3&&backup.skills.defaults.research==='imrad-reading');for(const version of [1,2,3,4,5,6])check('backup accepts version '+version,await run(`const z=await JSZip.loadAsync(await CangjingBackup.encode());const m=JSON.parse(await z.file('manifest.json').async('string'));m.version=${version};z.file('manifest.json',JSON.stringify(m));const s=await CangjingBackup.decode(await z.generateAsync({type:'uint8array'}));return s.books.length===1;`));
await button('返回文獻庫');await button('研究助理','.research-controls');check('assistant uses one panel for multi-page skills',await run('return !document.querySelector("#ai-panel").hidden&&!document.querySelector(".assistant-page-host").hidden&&!!document.querySelector(".research-skill-picker");'));await run('document.querySelector("[aria-label=自訂研究指令]").value="Compare the selected evidence.";');await button('送出指定頁面','#ai-panel');await sleep(2200);check('multi-page assistant returns usable result',await run('return document.querySelector(".assistant-page-host").textContent.includes("Synthetic research assistant response");'));await run('document.querySelector("#ai-panel").hidden=true;await openBook(records[0].id);');await sleep(400);check('original PDF bookmark and thumbnails preserved without AI TOC',await run('return document.querySelector("#toc").textContent.includes("頁面縮圖")&&!document.querySelector("#toc").textContent.includes("AI 目錄");'));await run(`ReaderAI.start('explain',{bookId:'${id}',title:'Synthetic study',chapter:'PDF 1',quote:'The study reports an association.',mode:'pdf',locator:{index:0}});`);await sleep(200);check('selection assistant shares same panel',await run('return document.querySelectorAll("#ai-panel").length===1&&document.querySelector(".ai-answer").textContent.includes("Synthetic research assistant response");'));
await run('document.querySelector("#ai-panel").hidden=true;await EvidenceWorkbenchUI.open();');await button('證據比較');await run('const p=document.querySelector("[aria-label=研究專案]");p.value="project-test";p.dispatchEvent(new Event("change"));const m=document.querySelector("[aria-label=證據矩陣版本]");m.value=m.options[1].value;m.dispatchEvent(new Event("change"));');await click('.evidence-statement');const shots=path.join(__dirname,'../outputs/verification-0.6.0');await fs.mkdir(shots,{recursive:true});for(const width of [390,768,1440,1920,2560]){const height=width===390?844:width===768?1024:width===1440?900:1080;await wc.debugger.sendCommand('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});await sleep(100);check('no outer horizontal overflow '+width,await run('return document.documentElement.scrollWidth<=innerWidth+1;'));const shot=await wc.debugger.sendCommand('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await fs.writeFile(path.join(shots,'matrix-'+width+'.png'),Buffer.from(shot.data,'base64'));}
await run('document.body.classList.add("dark");');await sleep(100);const dark=await wc.debugger.sendCommand('Page.captureScreenshot',{format:'png'});await fs.writeFile(path.join(shots,'matrix-dark.png'),Buffer.from(dark.data,'base64'));check('dark mode applied',await run('return getComputedStyle(document.body).getPropertyValue("--paper").trim()!=="#fff";'));
await wc.debugger.sendCommand('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await wc.debugger.sendCommand('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});check('keyboard focus reaches interactive control',await run('return ["BUTTON","SELECT","INPUT","TEXTAREA","A"].includes(document.activeElement.tagName);'));check('no renderer errors',errors.length===0);await fs.writeFile(path.join(shots,'ui-results.json'),JSON.stringify({checks,calls:calls.length,errors,semanticAccuracy:'not evaluated: synthetic model fixtures'},null,2));console.log(JSON.stringify({passed:checks.length,modelCalls:calls.length,errors,screenshots:shots}));app.exit(0);
}catch(e){console.error(e.stack);console.error(JSON.stringify({checks,errors}));app.exit(1);}});
setTimeout(()=>{console.error('UI timeout');app.exit(1);},120000).unref();
